/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-02 13:45:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "관리자 대쉬보드";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1716440579524L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>엘리시안 호텔 관리자 페이지</title>\r\n");
      out.write(" \r\n");
      out.write("<!-- favicon S -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/hotel_prj/admin/assets/static/images/logo/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<!-- favicon E -->\r\n");
      out.write("\r\n");
      out.write("<!-- template css S -->\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin href=\"/hotel_prj/admin/assets/compiled/css/app.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin href=\"/hotel_prj/admin/assets/compiled/css/app-dark.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin href=\"/hotel_prj/admin/assets/compiled/css/iconly.css\">\r\n");
      out.write("<!-- template css E -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery CDN S -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!-- jQuery CDN E -->\r\n");
      out.write("\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\".sidebar-item.db\").addClass(\"active\");\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.sidebar-item', function() {\r\n");
      out.write("	        // 모든 .sidebar-item 요소에서 active 클래스 제거\r\n");
      out.write("	        $(\".sidebar-item\").removeClass(\"active\");\r\n");
      out.write("	\r\n");
      out.write("	        // 클릭된 요소에만 active 클래스 추가\r\n");
      out.write("	        $(this).addClass(\"active\");\r\n");
      out.write("		});\r\n");
      out.write("	}); // ready\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/initTheme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- app S -->\r\n");
      out.write("<div id=\"app\">\r\n");
      out.write("	<!-- sidebar S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- sidebar E -->\r\n");
      out.write("		\r\n");
      out.write("	<!-- main S -->\r\n");
      out.write("	<div id=\"main\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- header S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- header E -->\r\n");
      out.write("            \r\n");
      out.write("	<div class=\"page-heading\">\r\n");
      out.write("	    <h3>DashBoard</h3>\r\n");
      out.write("	</div> \r\n");
      out.write("	\r\n");
      out.write("	<div class=\"page-content mb-3\"> \r\n");
      out.write("	    <section class=\"row\">\r\n");
      out.write("	        <div class=\"col-12 col-lg-9\">\r\n");
      out.write("	            <div class=\"row\">\r\n");
      out.write("	                <div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-body px-4 py-4-5\">\r\n");
      out.write("	                            <div class=\"row\">\r\n");
      out.write("	                                <div class=\"col-md-4 col-lg-12 col-xl-12 col-xxl-5 d-flex justify-content-start \">\r\n");
      out.write("	                                    <div class=\"stats-icon purple mb-2\">\r\n");
      out.write("	                                        <i class=\"iconly-boldShow\"></i>\r\n");
      out.write("	                                    </div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-md-8 col-lg-12 col-xl-12 col-xxl-7\">\r\n");
      out.write("	                                    <h6 class=\"text-muted font-semibold\">Profile Views</h6>\r\n");
      out.write("	                                    <h6 class=\"font-extrabold mb-0\">112.000</h6>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div> \r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("	                    <div class=\"card\"> \r\n");
      out.write("	                        <div class=\"card-body px-4 py-4-5\">\r\n");
      out.write("	                            <div class=\"row\">\r\n");
      out.write("	                                <div class=\"col-md-4 col-lg-12 col-xl-12 col-xxl-5 d-flex justify-content-start \">\r\n");
      out.write("	                                    <div class=\"stats-icon blue mb-2\">\r\n");
      out.write("	                                        <i class=\"iconly-boldProfile\"></i>\r\n");
      out.write("	                                    </div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-md-8 col-lg-12 col-xl-12 col-xxl-7\">\r\n");
      out.write("	                                    <h6 class=\"text-muted font-semibold\">Followers</h6>\r\n");
      out.write("	                                    <h6 class=\"font-extrabold mb-0\">183.000</h6>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-body px-4 py-4-5\">\r\n");
      out.write("	                            <div class=\"row\">\r\n");
      out.write("	                                <div class=\"col-md-4 col-lg-12 col-xl-12 col-xxl-5 d-flex justify-content-start \">\r\n");
      out.write("	                                    <div class=\"stats-icon green mb-2\">\r\n");
      out.write("	                                        <i class=\"iconly-boldAdd-User\"></i>\r\n");
      out.write("	                                    </div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-md-8 col-lg-12 col-xl-12 col-xxl-7\">\r\n");
      out.write("	                                    <h6 class=\"text-muted font-semibold\">Following</h6>\r\n");
      out.write("	                                    <h6 class=\"font-extrabold mb-0\">80.000</h6>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-body px-4 py-4-5\">\r\n");
      out.write("	                            <div class=\"row\">\r\n");
      out.write("	                                <div class=\"col-md-4 col-lg-12 col-xl-12 col-xxl-5 d-flex justify-content-start \">\r\n");
      out.write("	                                    <div class=\"stats-icon red mb-2\">\r\n");
      out.write("	                                        <i class=\"iconly-boldBookmark\"></i>\r\n");
      out.write("	                                    </div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-md-8 col-lg-12 col-xl-12 col-xxl-7\">\r\n");
      out.write("	                                    <h6 class=\"text-muted font-semibold\">Saved Post</h6>\r\n");
      out.write("	                                    <h6 class=\"font-extrabold mb-0\">112</h6>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"row\">\r\n");
      out.write("	                <div class=\"col-12\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-header\">\r\n");
      out.write("	                            <h4>Profile Visit</h4>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"card-body\">\r\n");
      out.write("	                            <div id=\"chart-profile-visit\"></div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"row\">\r\n");
      out.write("	                <div class=\"col-12 col-xl-4\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-header\">\r\n");
      out.write("	                            <h4>Profile Visit</h4>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"card-body\">\r\n");
      out.write("	                            <div class=\"row\">\r\n");
      out.write("	                                <div class=\"col-7\">\r\n");
      out.write("	                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                        <svg class=\"bi text-primary\" width=\"32\" height=\"32\" fill=\"blue\"\r\n");
      out.write("	                                            style=\"width:10px\">\r\n");
      out.write("	                                           <use\r\n");
      out.write("	                                               xlink:href=\"/hotel_prj/admin/assets/static/images/bootstrap-icons.svg#circle-fill\" />\r\n");
      out.write("	                                       </svg>\r\n");
      out.write("	                                       <h5 class=\"mb-0 ms-3\">Europe</h5>\r\n");
      out.write("	                                   </div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-5\">\r\n");
      out.write("	                                   <h5 class=\"mb-0 text-end\">862</h5>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-12\">\r\n");
      out.write("	                                   <div id=\"chart-europe\"></div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                           </div>\r\n");
      out.write("	                           <div class=\"row\">\r\n");
      out.write("	                               <div class=\"col-7\">\r\n");
      out.write("	                                   <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                       <svg class=\"bi text-success\" width=\"32\" height=\"32\" fill=\"blue\"\r\n");
      out.write("	                                           style=\"width:10px\">\r\n");
      out.write("	                                           <use\r\n");
      out.write("	                                               xlink:href=\"/hotel_prj/admin/assets/static/images/bootstrap-icons.svg#circle-fill\" />\r\n");
      out.write("	                                       </svg>\r\n");
      out.write("	                                       <h5 class=\"mb-0 ms-3\">America</h5>\r\n");
      out.write("	                                   </div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-5\">\r\n");
      out.write("	                                   <h5 class=\"mb-0 text-end\">375</h5>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-12\">\r\n");
      out.write("	                                   <div id=\"chart-america\"></div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                           </div>\r\n");
      out.write("	                           <div class=\"row\">\r\n");
      out.write("	                               <div class=\"col-7\">\r\n");
      out.write("	                                   <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                       <svg class=\"bi text-success\" width=\"32\" height=\"32\" fill=\"blue\"\r\n");
      out.write("	                                           style=\"width:10px\">\r\n");
      out.write("	                                           <use\r\n");
      out.write("	                                               xlink:href=\"/hotel_prj/admin/assets/static/images/bootstrap-icons.svg#circle-fill\" />\r\n");
      out.write("	                                       </svg>\r\n");
      out.write("	                                       <h5 class=\"mb-0 ms-3\">India</h5>\r\n");
      out.write("	                                   </div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-5\">\r\n");
      out.write("	                                   <h5 class=\"mb-0 text-end\">625</h5>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                               <div class=\"col-12\">\r\n");
      out.write("	                                   <div id=\"chart-india\"></div>\r\n");
      out.write("	                               </div>\r\n");
      out.write("	                           </div>\r\n");
      out.write("	                           <div class=\"row\">\r\n");
      out.write("	                               <div class=\"col-7\">\r\n");
      out.write("	                                   <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                       <svg class=\"bi text-danger\" width=\"32\" height=\"32\" fill=\"blue\"\r\n");
      out.write("	                                           style=\"width:10px\">\r\n");
      out.write("	                                            <use\r\n");
      out.write("	                                                xlink:href=\"/hotel_prj/admin/assets/static/images/bootstrap-icons.svg#circle-fill\" />\r\n");
      out.write("	                                        </svg>\r\n");
      out.write("	                                        <h5 class=\"mb-0 ms-3\">Indonesia</h5>\r\n");
      out.write("	                                    </div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-5\">\r\n");
      out.write("	                                    <h5 class=\"mb-0 text-end\">1025</h5>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"col-12\">\r\n");
      out.write("	                                    <div id=\"chart-indonesia\"></div>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-12 col-xl-8\">\r\n");
      out.write("	                    <div class=\"card\">\r\n");
      out.write("	                        <div class=\"card-header\">\r\n");
      out.write("	                            <h4>Latest Comments</h4>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"card-body\">\r\n");
      out.write("	                            <div class=\"table-responsive\">\r\n");
      out.write("	                                <table class=\"table table-hover table-lg\">\r\n");
      out.write("	                                    <thead>\r\n");
      out.write("	                                        <tr>\r\n");
      out.write("	                                            <th>Name</th>\r\n");
      out.write("	                                            <th>Comment</th>\r\n");
      out.write("	                                        </tr>\r\n");
      out.write("	                                    </thead>\r\n");
      out.write("	                                    <tbody>\r\n");
      out.write("	                                        <tr>\r\n");
      out.write("	                                            <td class=\"col-3\">\r\n");
      out.write("	                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                                    <div class=\"avatar avatar-md\">\r\n");
      out.write("	                                                        <img src=\"/hotel_prj/admin/assets/compiled/jpg/5.jpg\">\r\n");
      out.write("	                                                    </div>\r\n");
      out.write("	                                                    <p class=\"font-bold ms-3 mb-0\">Si Cantik</p>\r\n");
      out.write("	                                                </div>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                            <td class=\"col-auto\">\r\n");
      out.write("	                                                <p class=\" mb-0\">Congratulations on your graduation!</p>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                        </tr>\r\n");
      out.write("	                                        <tr>\r\n");
      out.write("	                                            <td class=\"col-3\">\r\n");
      out.write("	                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                                    <div class=\"avatar avatar-md\">\r\n");
      out.write("	                                                        <img src=\"/hotel_prj/admin/assets/compiled/jpg/2.jpg\">\r\n");
      out.write("	                                                    </div>\r\n");
      out.write("	                                                    <p class=\"font-bold ms-3 mb-0\">Si Ganteng</p>\r\n");
      out.write("	                                                </div>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                            <td class=\"col-auto\">\r\n");
      out.write("	                                                <p class=\" mb-0\">Wow amazing design! Can you make another tutorial for\r\n");
      out.write("	                                                    this design?</p>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                        </tr>\r\n");
      out.write("	                                        <tr>\r\n");
      out.write("	                                            <td class=\"col-3\">\r\n");
      out.write("	                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                                    <div class=\"avatar avatar-md\">\r\n");
      out.write("	                                                        <img src=\"/hotel_prj/admin/assets/compiled/jpg/8.jpg\">\r\n");
      out.write("	                                                    </div>\r\n");
      out.write("	                                                    <p class=\"font-bold ms-3 mb-0\">Singh Eknoor</p>\r\n");
      out.write("	                                                </div>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                            <td class=\"col-auto\">\r\n");
      out.write("	                                                <p class=\" mb-0\">What a stunning design! You are so talented and creative!</p>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                        </tr>\r\n");
      out.write("	                                        <tr>\r\n");
      out.write("	                                            <td class=\"col-3\">\r\n");
      out.write("	                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                                                    <div class=\"avatar avatar-md\">\r\n");
      out.write("	                                                        <img src=\"/hotel_prj/admin/assets/compiled/jpg/3.jpg\">\r\n");
      out.write("	                                                    </div>\r\n");
      out.write("	                                                    <p class=\"font-bold ms-3 mb-0\">Rani Jhadav</p>\r\n");
      out.write("	                                                </div>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                            <td class=\"col-auto\">\r\n");
      out.write("	                                                <p class=\" mb-0\">I love your design! It’s so beautiful and unique! How did you learn to do this?</p>\r\n");
      out.write("	                                            </td>\r\n");
      out.write("	                                        </tr>\r\n");
      out.write("	                                    </tbody>\r\n");
      out.write("	                                </table>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"col-12 col-lg-3\">\r\n");
      out.write("	            <div class=\"card\">\r\n");
      out.write("	                <div class=\"card-body py-4 px-4\">\r\n");
      out.write("	                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("	                        <div class=\"avatar avatar-xl\">\r\n");
      out.write("	                            <img src=\"/hotel_prj/admin/assets/compiled/jpg/1.jpg\" alt=\"Face 1\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"ms-3 name\">\r\n");
      out.write("	                            <h5 class=\"font-bold\">John Duck</h5>\r\n");
      out.write("	                            <h6 class=\"text-muted mb-0\">@johnducky</h6>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"card\">\r\n");
      out.write("	                <div class=\"card-header\">\r\n");
      out.write("	                    <h4>Recent Messages</h4>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"card-content pb-4\">\r\n");
      out.write("	                    <div class=\"recent-message d-flex px-4 py-3\">\r\n");
      out.write("	                        <div class=\"avatar avatar-lg\">\r\n");
      out.write("	                            <img src=\"/hotel_prj/admin/assets/compiled/jpg/4.jpg\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"name ms-4\">\r\n");
      out.write("	                            <h5 class=\"mb-1\">Hank Schrader</h5>\r\n");
      out.write("	                            <h6 class=\"text-muted mb-0\">@johnducky</h6>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"recent-message d-flex px-4 py-3\">\r\n");
      out.write("	                        <div class=\"avatar avatar-lg\">\r\n");
      out.write("	                            <img src=\"/hotel_prj/admin/assets/compiled/jpg/5.jpg\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"name ms-4\">\r\n");
      out.write("	                            <h5 class=\"mb-1\">Dean Winchester</h5>\r\n");
      out.write("	                            <h6 class=\"text-muted mb-0\">@imdean</h6>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"recent-message d-flex px-4 py-3\">\r\n");
      out.write("	                        <div class=\"avatar avatar-lg\">\r\n");
      out.write("	                            <img src=\"/hotel_prj/admin/assets/compiled/jpg/1.jpg\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"name ms-4\">\r\n");
      out.write("	                            <h5 class=\"mb-1\">John Dodol</h5>\r\n");
      out.write("	                            <h6 class=\"text-muted mb-0\">@dodoljohn</h6>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"px-4\">\r\n");
      out.write("	                        <button class='btn btn-block btn-xl btn-outline-primary font-bold mt-3'>Start Conversation</button>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div> \r\n");
      out.write("	            <div class=\"card\">\r\n");
      out.write("	                <div class=\"card-header\">\r\n");
      out.write("	                    <h4>Visitors Profile</h4>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"card-body\">\r\n");
      out.write("	                    <div id=\"chart-visitors-profile\"></div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- footer S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- footer E -->\r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- main E -->\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!-- app E  -->\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 필요 Script S -->\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/components/dark.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/compiled/js/app.js\"></script>\r\n");
      out.write("<!-- 공통 필요 Script E -->\r\n");
      out.write("     \r\n");
      out.write("<!-- Need: Apexcharts -->\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/pages/dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
