/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-04 04:53:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.resve;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class room_005fresve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "관리자 객실 예약 관리";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1716440579524L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>엘리시안 호텔 관리자 페이지</title>\r\n");
      out.write(" \r\n");
      out.write("<!-- favicon S -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/hotel_prj/admin/assets/static/images/logo/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<!-- favicon E -->\r\n");
      out.write("\r\n");
      out.write("<!-- datatable css S -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hotel_prj/admin/assets/extensions/datatables.net-bs5/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin=\"\" href=\"/hotel_prj/admin/assets/compiled/css/table-datatable-jquery.css\">\r\n");
      out.write("<!-- datatable css E -->\r\n");
      out.write("\r\n");
      out.write("<!-- template css S -->\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin href=\"/hotel_prj/admin/assets/compiled/css/app.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin href=\"/hotel_prj/admin/assets/compiled/css/app-dark.css\">\r\n");
      out.write("<!-- template css E -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery CDN S -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!-- jQuery CDN E -->\r\n");
      out.write("\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("#table1_wrapper {\r\n");
      out.write("	width:1470px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\".sidebar-item.rem\").addClass(\"active\");\r\n");
      out.write("		$(\".submenu-item.rrm\").addClass(\"active\");\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '.sidebar-item', function() {\r\n");
      out.write("	        // 모든 .sidebar-item 요소에서 active 클래스 제거\r\n");
      out.write("	        $(\".sidebar-item\").removeClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("	        // 클릭된 요소에만 active 클래스 추가\r\n");
      out.write("	        $(this).addClass(\"active\");\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    $(document).on('click', '.submenu-item', function() {\r\n");
      out.write("	        // 모든 .sidebar-item 요소에서 active 클래스 제거\r\n");
      out.write("	        $(\".submenu-item\").removeClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("	        // 클릭된 요소에만 active 클래스 추가\r\n");
      out.write("	        $(this).addClass(\"active\");\r\n");
      out.write("	    });\r\n");
      out.write("	}); // ready\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/initTheme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- app S -->\r\n");
      out.write("<div id=\"app\">\r\n");
      out.write("	<!-- sidebar S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- sidebar E -->\r\n");
      out.write("		\r\n");
      out.write("	<!-- main S -->\r\n");
      out.write("	<div id=\"main\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- header S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- header E -->\r\n");
      out.write("            \r\n");
      out.write("	<div class=\"page-heading\">\r\n");
      out.write("	    <h3>Room Reservation Management</h3>\r\n");
      out.write("	</div> \r\n");
      out.write("	\r\n");
      out.write("	<!-- Basic Tables start -->\r\n");
      out.write("    <section class=\"section\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table\" id=\"table1\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>예약번호</th>\r\n");
      out.write("                                <th>예약상태</th>\r\n");
      out.write("                                <th>상품명</th>\r\n");
      out.write("                                <th>체크인</th>\r\n");
      out.write("                                <th>체크아웃</th>\r\n");
      out.write("                                <th>예약일</th>\r\n");
      out.write("                                <th>예약자 영문이름</th>\r\n");
      out.write("                                <th>연락처</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Basic Tables end -->\r\n");
      out.write("\r\n");
      out.write("	<!-- footer S -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- footer E -->\r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- main E -->\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!-- app E  -->\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 필요 Script S -->\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/components/dark.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/compiled/js/app.js\"></script>\r\n");
      out.write("<!-- 공통 필요 Script E -->\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/datatables.net/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("<script src=\"/hotel_prj/admin/assets/static/js/pages/datatables.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		var table = $('#table1').DataTable();\r\n");
      out.write("\r\n");
      out.write("		// DataTable 인스턴스 제거\r\n");
      out.write("		table.destroy();\r\n");
      out.write("		\r\n");
      out.write("		var table = $('#table1').DataTable({\r\n");
      out.write("			ajax: {\r\n");
      out.write("		       'url':'DATA.json', \r\n");
      out.write("		       //'type': 'POST',\r\n");
      out.write("		       'dataSrc':''\r\n");
      out.write("		    },\r\n");
      out.write("			columns: [\r\n");
      out.write("				{\"data\": \"res_num\", \"width\": \"150px\"},\r\n");
      out.write("				{\"data\": \"room_res_status\", \"width\": \"130px\"},\r\n");
      out.write("				{\"data\": \"room\", \"width\": \"300px\"}, \r\n");
      out.write("				{\"data\": \"check_in\", \"width\": \"120px\"},\r\n");
      out.write("				{\"data\": \"check_out\", \"width\": \"120px\"},\r\n");
      out.write("				{\"data\": \"room_res_date\", \"width\": \"120px\"},\r\n");
      out.write("				{\"data\": \"eng_name\", \"width\": \"150px\"},\r\n");
      out.write("				{\"data\": \"guest_phone\", \"width\": \"150px\"}\r\n");
      out.write("			],\r\n");
      out.write("			dom:\r\n");
      out.write("				\"<'row'<'col-sm-12 col-md-11'f><'col-sm-12 col-md-1'l>>\" +\r\n");
      out.write("				\"<'row dt-row'<'col-sm-12'tr>>\" +\r\n");
      out.write("				\"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>\",\r\n");
      out.write("			language: {\r\n");
      out.write("		        emptyTable: \"데이터가 없습니다.\",\r\n");
      out.write("		        zeroRecords: \"데이터가 없습니다.\",\r\n");
      out.write("		        lengthMenu: \"_MENU_ 개\",\r\n");
      out.write("		        search: \"검색 \",\r\n");
      out.write("		        searchPlaceholder: \"검색어를 입력하세요.\",\r\n");
      out.write("		        paginate: {\r\n");
      out.write("		            \"next\": \"다음\",\r\n");
      out.write("		            \"previous\": \"이전\"\r\n");
      out.write("		        },\r\n");
      out.write("		        info: \"현재 _START_ - _END_ / 총 _TOTAL_건\",\r\n");
      out.write("		        infoEmpty: \"데이터 없음\",\r\n");
      out.write("		        infoFiltered: \"( _MAX_건의 데이터에서 필터링됨 )\",\r\n");
      out.write("		        loadingRecords: \"로딩중...\",\r\n");
      out.write("		        processing:     \"잠시만 기다려 주세요...\"\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#table1_wrapper').find('input[type=\"search\"]').removeClass('form-control-sm');\r\n");
      out.write("		\r\n");
      out.write("		$('#table1_filter').prepend('검색 조건<select id=\"select\" class=\"form-select\" style=\"width: 200px; display: inline; margin: 0px 20px 0px 10px;\"></select>');\r\n");
      out.write("	    $('#table1 > thead > tr').children().each(function (indexInArray, valueOfElement) { \r\n");
      out.write("	        $('#select').append('<option>'+valueOfElement.innerHTML+'</option>');\r\n");
      out.write("	    });\r\n");
      out.write("		\r\n");
      out.write("	    $('.dataTables_filter input').unbind().bind('keyup cut', function () {\r\n");
      out.write("	        var colIndex = document.querySelector('#select').selectedIndex;\r\n");
      out.write("	        table.column(colIndex).search(this.value).draw();\r\n");
      out.write("	    });\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
