/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-23 06:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.asd.admin.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "명화관 관리자 로그인";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>명화관 관리자 페이지</title>\r\n");
      out.write("<link rel = \"icon\" href = \"http://localhost/theater_prj/asd/favicon.ico\">\r\n");
      out.write("<!--bootstrap 시작-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--bootstrap 끝-->\r\n");
      out.write("<!--jQuery CDN 시작-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--jQuery CDN 끝-->\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"../vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"../css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--외부CSS끝-->\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("    $(\"#inputId\").focus();\r\n");
      out.write("    $(\"#inputId\").on('keypress', function(e) {\r\n");
      out.write("        if (e.which === 13) {\r\n");
      out.write("            e.preventDefault(); \r\n");
      out.write("            let id = $(\"#inputId\").val();\r\n");
      out.write("            if (id === \"\") {\r\n");
      out.write("                alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#inputPassword\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\"#inputPassword\").on('keypress', function(e) {\r\n");
      out.write("        if (e.which === 13) { \r\n");
      out.write("            e.preventDefault(); \r\n");
      out.write("            let pw = $(\"#inputPassword\").val();\r\n");
      out.write("            if (pw === \"\") {\r\n");
      out.write("                alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#submit\").click();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}); // ready\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function checkNull(){\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		//alert(\"클릭되었음\")\r\n");
      out.write("		let id = $(\"#inputId\").val();\r\n");
      out.write("		let pw = $(\"#inputPassword\").val();\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	    // ID나 비밀번호가 비어 있는지 확인\r\n");
      out.write("	    if(id === \"\" && pw === \"\") {\r\n");
      out.write("	        alert(\"ID와 비밀번호를 입력해주세요.\");\r\n");
      out.write("	        return false;\r\n");
      out.write("	    } else if(id === \"\") {\r\n");
      out.write("	        alert(\"ID를 입력해주세요.\");\r\n");
      out.write("	        $(\"#inputId\").focus();\r\n");
      out.write("	        return false; \r\n");
      out.write("	    } else if(pw === \"\") {\r\n");
      out.write("	        alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("	        $(\"#inputPassword\").focus();\r\n");
      out.write("	        \r\n");
      out.write("	        return false; \r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gradient-primary\" style = \"margin-top:200px; background-color:#fff;background-image: linear-gradient(180deg,#fff 10%,#fff 100%);\" >\r\n");
      out.write("<!-- S 로그인 세션 확인  -->\r\n");
      out.write("<!-- prevPage에 값이 있다면 이전페이지 저장 -->\r\n");
      out.write("<!-- 저장되어있지 않다면 기본값 dashboard.jsp로 저장 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

String prevPage ="";
String id = (String)session.getAttribute("adminId");




if (request.getParameter("prevPage")==null){
	prevPage="dashboard.jsp";
}else{
	prevPage=request.getParameter("prevPage");
}




if (id != null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("var prevPage = \"");
      out.print( prevPage );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("window.location.href = prevPage;\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- E 로그인 세션 확인  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Outer Row -->\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-xl-10 col-lg-12 col-md-9\">\r\n");
      out.write("                <div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("                    <div class=\"card-body p-0\">\r\n");
      out.write("                        <!-- Nested Row within Card Body -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 d-none d-lg-block bg-login-image\" style = \"margin: auto; padding-left: 120px;\">\r\n");
      out.write("                            <img src=\"http://localhost/theater_prj/asd/logo.png\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"p-5\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <h1 class=\"h4 text-gray-900 mb-4\">Admin Page Login</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <form class=\"user\" action=\"loginService.jsp\" method=\"post\" onsubmit=\"return checkNull()\">\r\n");
      out.write("									    <div class=\"form-group\">\r\n");
      out.write("									        <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("									            id=\"inputId\" name=\"inputId\" aria-describedby=\"emailHelp\"\r\n");
      out.write("									            placeholder=\"ID\">\r\n");
      out.write("									    </div>\r\n");
      out.write("									    <div class=\"form-group\">\r\n");
      out.write("									        <input type=\"password\" class=\"form-control form-control-user\"\r\n");
      out.write("									            id=\"inputPassword\" name=\"inputPassword\"  placeholder=\"Password\">\r\n");
      out.write("									    </div>\r\n");
      out.write("									    <div>\r\n");
      out.write("									    <button type=\"submit\" id=\"submit\" class=\"btn btn-primary btn-user btn-block\">\r\n");
      out.write("									        Login\r\n");
      out.write("									    </button>\r\n");
      out.write("									    </div>\r\n");
      out.write("									    <div style=\"display: flex;\">\r\n");
      out.write("									    <a href = \"../../jsp/index.html\" style=\"font-size: 13px; margin: 0px auto; margin-top: 10px;\">영화관홈</a>\r\n");
      out.write("									    </div>\r\n");
      out.write("									    <input type=\"hidden\" id=\"prevPage\" name=\"prevPage\" required=\"required\"  value=");
      out.print( prevPage );
      out.write(" >\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"../vendor/bootstrap/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery-easing/jquery.easing.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"../js/sb-admin-2.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
