/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-22 09:52:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.asd.admin.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.sql.SQLException;
import VO.AdminMovieVO;
import java.util.List;
import admin.ScreeningDAO1;
import admin.AdminMovieDAO;
import java.util.ArrayList;
import java.util.List;
import java.sql.SQLException;
import admin.ScreeningDAO1;

public final class movie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "명화관 관리자 회원관리";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1715750612809L));
    _jspx_dependants.put("/asd/admin/jsp/sidebar.jsp", Long.valueOf(1715754754189L));
    _jspx_dependants.put("/asd/admin/jsp/footer.jsp", Long.valueOf(1715750612819L));
    _jspx_dependants.put("/asd/admin/jsp/topbar.jsp", Long.valueOf(1715750612819L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/theater_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/asd/admin/jsp/movie_registerForm.jsp", Long.valueOf(1715875733281L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("admin.ScreeningDAO1");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("admin.AdminMovieDAO");
    _jspx_imports_classes.add("VO.AdminMovieVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>명화관 관리자 페이지</title>\r\n");
      out.write("<link rel = \"icon\" href = \"http://localhost/theater_prj/asd/favicon.ico\">\r\n");
      out.write("<!--bootstrap 시작-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--bootstrap 끝-->\r\n");
      out.write("<!--jQuery CDN 시작-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--jQuery CDN 끝-->\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"../vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"../css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("    	\r\n");
      out.write("\r\n");
      out.write("        // 검색 버튼 클릭 이벤트 핸들러\r\n");
      out.write("        $(\"#searchButton\").click(searchButtonClick);\r\n");
      out.write("\r\n");
      out.write("        // 엔터키 입력 이벤트 핸들러\r\n");
      out.write("        $(\"#searchText\").keypress(function(event) {\r\n");
      out.write("            if (event.which === 13) {\r\n");
      out.write("                searchButtonClick();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function searchButtonClick() {\r\n");
      out.write("            var param = {\r\n");
      out.write("                searchType: $(\"#searchType\").val(),\r\n");
      out.write("                searchText: $(\"#searchText\").val()\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"movie_service.jsp\",\r\n");
      out.write("                type: \"get\",\r\n");
      out.write("                data: param,\r\n");
      out.write("                dataType: \"JSON\",\r\n");
      out.write("                success: function(jsonArr) {\r\n");
      out.write("                    // 검색 결과를 테이블에 반영\r\n");
      out.write("                    updateTable(jsonArr);\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr) {\r\n");
      out.write("                    alert(xhr.statusText);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        //$(\"#contentBoard\").on(\"click\", \"tr\", clickTable);\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("        $(\"#registerButton\").click(function() {\r\n");
      out.write("            $(\"#registerForm\").show();\r\n");
      out.write("            $(\"#table-content\").hide();\r\n");
      out.write("            $(\"#editForm\").hide();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $(\"#toBack\").click(function() {\r\n");
      out.write("            $(\"#registerForm\").hide();\r\n");
      out.write("            $(\"#editForm\").hide();\r\n");
      out.write("            $(\"#table-content\").show();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        function clickTable(mCode, poster, rDate,rTime) {\r\n");
      out.write("            // 클릭한 테이블의 정보를 가져오는 코드\r\n");
      out.write("            $(\"#registerForm\").hide();\r\n");
      out.write("            $(\"#table-content\").hide();\r\n");
      out.write("            $(\"#editForm\").show();\r\n");
      out.write("            \r\n");
      out.write("            var param = {\r\n");
      out.write("                    tableMovieCode: mCode,\r\n");
      out.write("                    action: \"table\"\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: \"edit_movie_service.jsp\",\r\n");
      out.write("                    type: \"get\",\r\n");
      out.write("                    data: param,\r\n");
      out.write("                    dataType: \"JSON\",\r\n");
      out.write("                    success: function(jsonArr) {\r\n");
      out.write("                        // 검색 결과를 테이블에 반영\r\n");
      out.write("                    	$(\"#eMovieCode\").val(jsonArr.movieCode);\r\n");
      out.write("                    	$(\"#movie_title_edit\").val(jsonArr.movieTitle);\r\n");
      out.write("                    	$(\"#movie_genre_edit\").val(jsonArr.movieGenre);\r\n");
      out.write("                    	$(\"#movie_director_edit\").val(jsonArr.movieDirector);\r\n");
      out.write("                    	$(\"#movie_main_actor_edit\").val(jsonArr.movieMainActor);\r\n");
      out.write("                    	$(\"#movie_sub_actor_edit\").val(jsonArr.movieSubActor);\r\n");
      out.write("                    	//$(\"#movie_release_date_edit\").val(jsonArr.editMovieReleaseDate);\r\n");
      out.write("                    	$(\"#movie_release_date_edit\").val(rDate);\r\n");
      out.write("                    	$(\"#movie_rating_edit\").val(jsonArr.movieRating);\r\n");
      out.write("                    	$(\"#movie_distributor_edit\").val(jsonArr.movieDistributor);\r\n");
      out.write("                    	$(\"#movie_running_time_edit\").val(jsonArr.movieRunningTime);\r\n");
      out.write("                    	$(\"#movie_description_edit\").val(jsonArr.movieDescription);\r\n");
      out.write("                    	//$(\"#movie_poster_edit\").val(jsonArr.moviePosterPath);\r\n");
      out.write("                    	$(\"#movie_poster_edit\").val(poster);\r\n");
      out.write("                    	$(\"#movie_status_edit\").val(jsonArr.movieScreeningStatus);\r\n");
      out.write("                    	/* if (jsonArr.movieScreeningStatus === \"Y\") {\r\n");
      out.write("		                    $(\"#movie_status_edit\").val(\"Y\");\r\n");
      out.write("		                } else {\r\n");
      out.write("		                    $(\"#movie_status_edit\").val(\"N\");\r\n");
      out.write("		                } */\r\n");
      out.write("                        console.log(jsonArr.movieTitle);\r\n");
      out.write("                        console.log(jsonArr.editMovieReleaseDate);\r\n");
      out.write("                        console.log(jsonArr.moviePosterPath);\r\n");
      out.write("                        console.log(jsonArr.moviePosterPath);\r\n");
      out.write("                        \r\n");
      out.write("                    },\r\n");
      out.write("                    error: function(xhr) {\r\n");
      out.write("                        alert(xhr.statusText);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("        }\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("        function updateTable(jsonArr) {\r\n");
      out.write("            // id=\"content\"를 삭제하고\r\n");
      out.write("            $(\"#contentBoard\").empty();\r\n");
      out.write("            // jsonArr를 반복하고, jsonObject을 parsing하여\r\n");
      out.write("            jsonArr.forEach(function(movie) {\r\n");
      out.write("                var status = \"\";\r\n");
      out.write("                if (movie.movieScreeningStatus === \"Y\") {\r\n");
      out.write("                    if (new Date(movie.movieReleaseDate) > new Date()) {\r\n");
      out.write("                        status = \"<span style=\\\"color: red;\\\">상영예정</span>\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        status = \"상영중\"; \r\n");
      out.write("                    }\r\n");
      out.write("                } else {\r\n");
      out.write("                    status = \"<span style=\\\"color: blue;\\\">상영완료</span>\";\r\n");
      out.write("                }\r\n");
      out.write("                var newRow = \"<tr onclick=\\\"clickTable('\" + movie.movieCode + \"', '\" + movie.movieTitle + \"','\" + movie.movieGenre + \"','\" + movie.movieDistributor + \"', '\" + movie.movieDirector + \"','\" + movie.movieRunningTime + \"','\" + movie.movieMainActor + \"','\" + movie.movieSubActor + \"','\" + movie.movieDescription + \"','\" + movie.moviePosterPath + \"','\" + movie.movieReleaseDate + \"','\" + movie.movieRating + \"','\" + movie.movieScreeningStatus + \"')\\\">\" +\r\n");
      out.write("                    \"<td>\" + movie.movieCode + \"</td>\" + // 결과 번호를 표시합니다.\r\n");
      out.write("                    \"<td>\" + movie.movieTitle + \"</td>\" +\r\n");
      out.write("                    \"<td>\" + status + \"</td>\" +\r\n");
      out.write("                    \"<td>\" + movie.movieGenre + \"</td>\" +\r\n");
      out.write("                    \"</tr>\";\r\n");
      out.write("                // id=\"content\"에 붙입니다.\r\n");
      out.write("                $(\"#contentBoard\").append(newRow);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("  //  });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

	String sbid = (String)session.getAttribute("adminId");

      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"http://localhost/theater_prj/asd/admin/jsp/dashboard.jsp\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\"><span>");
      out.print(sbid);
      out.write("</span>님</div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">로그인 중</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Dashboard -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/dashboard.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("                    <span>대시보드</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/movie.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>영화관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 상영관리 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/screening.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>상영 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 상영관관리 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/theater.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>상영관 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 회원관리 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/member.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>회원 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 예매관리 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/reservation.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>예매 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - 공지사항관리 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/notice.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>공지사항 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 자주찾는질문 -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"http://localhost/theater_prj/asd/admin/jsp/question.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>자주찾는질문</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("               ");
      out.write('\r');
      out.write('\n');

	String tbid = (String)session.getAttribute("adminId");

      out.write("\r\n");
      out.write("<!-- Topbar -->\r\n");
      out.write("       <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("           <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("           <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("               <i class=\"fa fa-bars\"></i>\r\n");
      out.write("           </button>\r\n");
      out.write("\r\n");
      out.write("           <!-- Topbar Navbar -->\r\n");
      out.write("           <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("               <!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("               <li class=\"nav-item dropdown no-arrow d-sm-none\">\r\n");
      out.write("                   <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\"\r\n");
      out.write("                       data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                       <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!-- Dropdown - Messages -->\r\n");
      out.write("                   <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("                       aria-labelledby=\"searchDropdown\">\r\n");
      out.write("                       <form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("                           <div class=\"input-group\">\r\n");
      out.write("                               <input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("                                   placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("                                   aria-describedby=\"basic-addon2\">\r\n");
      out.write("                               <div class=\"input-group-append\">\r\n");
      out.write("                                   <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                                       <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("                                   </button>\r\n");
      out.write("                               </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </form>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </li>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("               <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("               <!-- Nav Item - User Information -->\r\n");
      out.write("               <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("                   <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\r\n");
      out.write("                       data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                       \r\n");
      out.write("                       <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
      out.print(tbid);
      out.write("</span>\r\n");
      out.write("                       <img class=\"img-profile rounded-circle\"\r\n");
      out.write("                           src=\"http://localhost/theater_prj/asd/admin/img/undraw_profile.svg\">\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!-- Dropdown - User Information -->\r\n");
      out.write("                   <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("                       aria-labelledby=\"userDropdown\">\r\n");
      out.write("                       <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\r\n");
      out.write("                           <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("                           Logout\r\n");
      out.write("                       </a>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </li>\r\n");
      out.write("\r\n");
      out.write("           </ul>\r\n");
      out.write("\r\n");
      out.write("       </nav>\r\n");
      out.write("<!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("<!-- Logout Modal-->\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">로그아웃하시겠습니까?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\"Logout\" 버튼을 누르면 로그아웃됩니다.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"logout.jsp\">Logout</a>\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Begin Page Content -->\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("	                <!-- Page Heading -->\r\n");
      out.write("	                <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("	                    <h1 class=\"h3 mb-0 text-gray-800\">영화관리</h1>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <!-- 영화관리 밑 컨텐츠 -->\r\n");
      out.write("				    <div id=\"table-content\" class=\"table-responsive\">\r\n");
      out.write("				    <!-- 검색 폼 -->\r\n");
      out.write("                    <form id=\"searchForm\" method=\"post\" action=\"movie_service.jsp\" class=\"row align-items-center\">\r\n");
      out.write("					    <!-- 지점 드롭다운 메뉴 -->\r\n");
      out.write("					    <select id=\"searchType\" class=\"form-select form-select-sm col-sm-1\" aria-label=\"Large select example\">\r\n");
      out.write("					        <option value=\"movie_title\">영화명</option>\r\n");
      out.write("					        <option value=\"movie_genre\">장르</option>\r\n");
      out.write("					    </select>\r\n");
      out.write("					    <input type=\"text\" id=\"searchText\" class=\"form-control col-sm-1\">\r\n");
      out.write("					    <button type=\"button\" id=\"searchButton\" class=\"btn btn-info col-sm-1\">검색</button>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				    <button id=\"registerButton\" class=\"btn btn-info float-right\">등록</button>\r\n");
      out.write("				        <table class=\"table table-striped table-hover\">\r\n");
      out.write("						    <thead>\r\n");
      out.write("						        <tr>\r\n");
      out.write("						            <th>코드</th>\r\n");
      out.write("						            <th>영화명</th>\r\n");
      out.write("						            <th>상영상태</th>\r\n");
      out.write("						            <th>장르</th>\r\n");
      out.write("						        </tr>\r\n");
      out.write("						    </thead>\r\n");
      out.write("						    <tbody id=\"contentBoard\">\r\n");
      out.write("							   ");

							   try {
							       AdminMovieDAO movieDAO = AdminMovieDAO.getInstance();
							       List<AdminMovieVO> movieList = movieDAO.selectMovieList();
							       for (AdminMovieVO movie : movieList) {
							           String status = ""; // 상영 상태
							           if (movie.getMovieScreeningStatus().equals("Y")) {
							               if (movie.getMovieReleaseDate().compareTo(new Date()) > 0) {
							                   // 상영예정 releast날짜가 현재 날짜보다 뒤일 때
							                   status = "<span style=\"color: red;\">상영예정</span>";
							               } else {
							                   // 상영중 현재 날짜보다 앞일 때
							                   status = "상영중";
							               }
							           } else {
							               // 상영예정 'N'
							               status = "<span style=\"color: blue;\">상영완료</span>";
							           }
							   
      out.write("\r\n");
      out.write("							   ");
      out.write("\r\n");
      out.write("							   <tr onClick=\"clickTable('");
      out.print(movie.getMovieCode());
      out.write("', '");
      out.print(movie.getMoviePosterPath());
      out.write("', '");
      out.print(movie.getMovieReleaseDate());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(movie.getMovieRunningTime());
      out.write("')\">\r\n");
      out.write("							       <td>");
      out.print(movie.getMovieCode());
      out.write("</td>\r\n");
      out.write("							       <td>");
      out.print(movie.getMovieTitle());
      out.write("</td>\r\n");
      out.write("							       <td>");
      out.print(status);
      out.write("</td>\r\n");
      out.write("							       <td>");
      out.print(movie.getMovieGenre());
      out.write("</td>\r\n");
      out.write("							   </tr>\r\n");
      out.write("							   ");

							       }
							   } catch (SQLException e) {
							       e.printStackTrace();
							   }
							   
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("\r\n");
      out.write("						</table>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <!-- 영화관리 밑 컨텐츠 -->\r\n");
      out.write("				    <div id=\"registerForm\" style=\"display:none;\">\r\n");
      out.write("				    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>영화 등록</title>\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .left,\r\n");
      out.write("        .right {\r\n");
      out.write("            width: 45%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#addNewMovie\").click(function () {\r\n");
      out.write("            	var posterPath = $(\"#movie_poster_add\").val().replace(/^.*[\\\\\\/]/, '');\r\n");
      out.write("                var param = {\r\n");
      out.write("                		movieTitle: $(\"#movie_title_add\").val(),\r\n");
      out.write("                        movieGenre: $(\"#movie_genre_add\").val(),\r\n");
      out.write("                        movieDirector: $(\"#movie_director_add\").val(),\r\n");
      out.write("                        movieMainActor: $(\"#movie_main_actor_add\").val(),\r\n");
      out.write("                        movieSubActor: $(\"#movie_sub_actor_add\").val(),\r\n");
      out.write("                        movieReleaseDate: $(\"#movie_release_date_add\").val(), // 개봉일자\r\n");
      out.write("                        movieRating: $(\"#movie_rating_add\").val(), // 관람등급\r\n");
      out.write("                        movieDistributor: $(\"#movie_distributor_add\").val(), // 배급사\r\n");
      out.write("                        movieRunningTime: $(\"#movie_running_time_add\").val(), // 러닝타임\r\n");
      out.write("                        movieDescription: $(\"#movie_description_add\").val(), // 줄거리\r\n");
      out.write("                        moviePosterPath: posterPath, // 포스터\r\n");
      out.write("                        movieScreeningStatus: $(\"#movie_status_add\").val() // 상영상태\r\n");
      out.write("                    \r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: \"movie_register_service.jsp\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    data: param,\r\n");
      out.write("                    success: function (response) {\r\n");
      out.write("                        alert(\"영화저장 성공\");\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function (xhr, status, error) {\r\n");
      out.write("                        alert(\"오류 발생: \" + error);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h1>영화 등록</h1>\r\n");
      out.write("    <hr />\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- 왼쪽 영역 -->\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <form id=\"addNewMomieForm\" class=\"pt-3\" style=\"max-width: 90%;\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    영화명 : <input type=\"text\" id=\"movie_title_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    장르 : <input type=\"text\" id=\"movie_genre_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    감독 : <input type=\"text\" id=\"movie_director_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    주연 : <input type=\"text\" id=\"movie_main_actor_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    조연 : <input type=\"text\" id=\"movie_sub_actor_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    개봉일자 : <input type=\"text\" id=\"movie_release_date_add\" placeholder=\"YYYY-MM-DD\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 오른쪽 영역 -->\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                    관람등급 : <select id=\"movie_rating_add\" >\r\n");
      out.write("                    	<option value=\"All\">전체관람가</option>\r\n");
      out.write("                    	<option value=\"12\">12세관람가</option>\r\n");
      out.write("                    	<option value=\"15\">15세관람가</option>\r\n");
      out.write("                    	<option value=\"18\">청소년관람불가</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    배급사 : <input type=\"text\" id=\"movie_distributor_add\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    러닝타임 : <input type=\"text\" id=\"movie_running_time_add\" placeholder=\"mm분\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    줄거리 : <textarea id=\"movie_description_add\" class=\"form-control\" rows=\"5\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    포스터 : <input type=\"file\" class=\"form-control\" id=\"movie_poster_add\" aria-describedby=\"inputGroupFileAddon03\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    상영상태 : <select id=\"movie_status_add\">\r\n");
      out.write("                    	<option value=\"Y\">상영가능</option>\r\n");
      out.write("                    	<option value=\"N\">상영불가</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<input type=\"button\" id=\"addNewMovie\" class=\"btn btn-info\" value=\"영화 등록\" />\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div id=\"editForm\" style=\"display:none;\">\r\n");
      out.write("				    ");
      out.write("\r\n");
      out.write("				    ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div></br><button id=\"toBack\" class=\"btn btn-warning\">뒤로</button></div>\r\n");
      out.write("                <!-- /.container-fluid -->\r\n");
      out.write("				\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; SAVE ME 2024</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"../vendor/bootstrap/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery-easing/jquery.easing.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--     Custom scripts for all pages\r\n");
      out.write("    <script src=\"./\"></script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /asd/admin/jsp/movie.jsp(259,8) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("movie_edit_form.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
