/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-22 09:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.asd.admin.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import admin.ScreeningVO;
import admin.ScreeningDAO1;
import java.util.ArrayList;

public final class screening_005fedit_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1715750612809L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/theater_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("admin.ScreeningDAO1");
    _jspx_imports_classes.add("admin.ScreeningVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>상영 수정</title>\r\n");
      out.write("    <!-- 필요한 CSS 및 JavaScript 라이브러리 링크 및 스타일 시트 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\"#editScreening\").click(function() {\r\n");
      out.write("            var param = {\r\n");
      out.write("                screeningCode: $(\"#eScreeningCode\").val(),\r\n");
      out.write("                theaterName: $(\"#eTheaterName\").val(),\r\n");
      out.write("                screeningRoom: $(\"#eTheaterNumber\").val(),\r\n");
      out.write("                movieName: $(\"#eMovieName\").val(),\r\n");
      out.write("                openDate: $(\"#eOpenDate\").val().replaceAll(\"-\",\"\"),\r\n");
      out.write("                screeningRound: $(\"#eScreeningRound\").val(),\r\n");
      out.write("                action: \"update\" // 업데이트 액션 지정\r\n");
      out.write("            };\r\n");
      out.write("    \r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"edit_screening_service.jsp\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                data: param,\r\n");
      out.write("                dataType: \"JSON\",\r\n");
      out.write("                success: function(result) {\r\n");
      out.write("                    alert(\"저장되었습니다\");\r\n");
      out.write("                    location.reload(true);\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr) {\r\n");
      out.write("                    alert(xhr.statusText);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        $(\"#deleteScreening\").click(function() {\r\n");
      out.write("            var param = {\r\n");
      out.write("                screeningCode: $(\"#eScreeningCode\").val(),\r\n");
      out.write("                action: \"delete\" // 삭제 액션 지정\r\n");
      out.write("            };\r\n");
      out.write("    \r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"edit_screening_service.jsp\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                data: param,\r\n");
      out.write("                dataType: \"JSON\",\r\n");
      out.write("                success: function(result) {\r\n");
      out.write("                    alert(\"삭제되었습니다\");\r\n");
      out.write("                    location.reload(true);\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr) {\r\n");
      out.write("                    alert(xhr.statusText);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");




      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>상영 수정</h1>\r\n");
      out.write("<hr/>\r\n");
      out.write("<form id=\"editScreeningForm\" class=\"pt-3\" style=\"max-width:920px;\">\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"theaterName\">지점:</label>\r\n");
      out.write("        <input type=\"text\" id=\"eTheaterName\" name=\"theaterName\" class=\"form-control\" value=\"\" readonly>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"TheaterNumber\">상영관:</label>\r\n");
      out.write("        <input type=\"text\" id=\"eTheaterNumber\" name=\"theaterNumber\" class=\"form-control\" value=\"\" readonly>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"movieName\">영화명:</label>\r\n");
      out.write("        <input type=\"text\" id=\"eMovieName\" name=\"movieName\" class=\"form-control\" value=\"\" readonly>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"openDate\">상영 시작일:</label>\r\n");
      out.write("        <input type=\"date\" id=\"eOpenDate\" name=\"openDate\" class=\"form-control\" value=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        상영시작시간 : \r\n");
      out.write("        <select id=\"eScreeningRound\" name=\"screeningRound\" class=\"form-select\" aria-label=\"Default select example\">\r\n");
      out.write("            <option value=\"1\">09:00 ~ 12:00</option>\r\n");
      out.write("            <option value=\"2\">12:00 ~ 15:00</option>\r\n");
      out.write("            <option value=\"3\">15:00 ~ 18:00</option>\r\n");
      out.write("            <option value=\"4\">18:00 ~ 21:00</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("	<input type=\"hidden\" id=\"eScreeningCode\" name=\"screeningCode\">\r\n");
      out.write("    <br/>\r\n");
      out.write("    <div>\r\n");
      out.write("        <!-- 수정 버튼 -->\r\n");
      out.write("        <input type=\"button\" id=\"editScreening\" class=\"btn btn-info\" value=\"상영 수정\">\r\n");
      out.write("        <!-- 삭제 버튼 -->\r\n");
      out.write("        <input type=\"button\" id=\"deleteScreening\" class=\"btn btn-warning\" value=\"상영 삭제\">\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	/*\r\n");
      out.write("    $(\"#editScreening\").click(function() {\r\n");
      out.write("        // 수정할 상영 정보 가져오기\r\n");
      out.write("        var param = {\r\n");
      out.write("            theaterName: $(\"#theaterName\").val(),\r\n");
      out.write("            screeningRoom: $(\"#screeningRoom\").val(),\r\n");
      out.write("            movieName: $(\"#movieName\").val(),\r\n");
      out.write("            openDate: $(\"#openDate\").val().replaceAll(\"-\",\"\"),\r\n");
      out.write("            screeningRound: $(\"#screeningRound\").val()\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"edit_screening_service.jsp\", // 수정 요청을 처리할 서블릿 주소\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            data: param,\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                alert(\"성공적으로 수정\");\r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                alert(\"오류 발생: \" + error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("	*/\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
