/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-03 08:09:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class room_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "관리자 객실 관리";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1716440579524L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>엘리시안 호텔 관리자 페이지</title>\r\n");
      out.write("\r\n");
      out.write("<!-- favicon S -->\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"/hotel_prj/admin/assets/static/images/logo/favicon.ico\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("<!-- favicon E -->\r\n");
      out.write("\r\n");
      out.write("<!-- template css S -->\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin\r\n");
      out.write("	href=\"/hotel_prj/admin/assets/compiled/css/app.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin\r\n");
      out.write("	href=\"/hotel_prj/admin/assets/compiled/css/app-dark.css\">\r\n");
      out.write("<link rel=\"stylesheet\" crossorigin\r\n");
      out.write("	href=\"/hotel_prj/admin/assets/compiled/css/iconly.css\">\r\n");
      out.write("<!-- template css E -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery CDN S -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!-- jQuery CDN E -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!-- /*grid to table*/\r\n");
      out.write(".grid-thead {\r\n");
      out.write("	display: grid;\r\n");
      out.write("	grid-template-columns: 5% 45% 10% 10% 10% 10% 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".grid-tbody {\r\n");
      out.write("	display: grid;\r\n");
      out.write("	grid-template-columns: 5% 45% 10% 10% 10% 10% 10%;\r\n");
      out.write("}\r\n");
      out.write("#table1_wrapper {\r\n");
      out.write("	width:1470px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\".sidebar-item.rm\").addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("		$(document).on('click', '.sidebar-item', function() {\r\n");
      out.write("			// 모든 .sidebar-item 요소에서 active 클래스 제거\r\n");
      out.write("			$(\".sidebar-item\").removeClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("			// 클릭된 요소에만 active 클래스 추가\r\n");
      out.write("			$(this).addClass(\"active\");\r\n");
      out.write("		});\r\n");
      out.write("	}); // ready\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<script src=\"/hotel_prj/admin/assets/static/js/initTheme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- app S -->\r\n");
      out.write("	<div id=\"app\">\r\n");
      out.write("		<!-- sidebar S -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- sidebar E -->\r\n");
      out.write("\r\n");
      out.write("		<!-- main S -->\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("			<!-- header S -->\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("			<!-- header E -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"page-heading\">\r\n");
      out.write("				<div class=\"page-title\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12 col-md-6 order-md-1 order-last\">\r\n");
      out.write("							<h3>객실 관리</h3>\r\n");
      out.write("							<p class=\"text-subtitle text-muted\">Powerful interactive\r\n");
      out.write("								tables with datatables (jQuery required).</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-md-6 order-md-2 order-first\">\r\n");
      out.write("							<nav aria-label=\"breadcrumb\"\r\n");
      out.write("								class=\"breadcrumb-header float-start float-lg-end\">\r\n");
      out.write("								<ol class=\"breadcrumb\">\r\n");
      out.write("									<li class=\"breadcrumb-item\"><a href=\"index.html\">Dashboard</a></li>\r\n");
      out.write("									<li class=\"breadcrumb-item active\" aria-current=\"page\">DataTable\r\n");
      out.write("										jQuery</li>\r\n");
      out.write("								</ol>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"page-content mb-3\">\r\n");
      out.write("					<!-- Basic Tables start -->\r\n");
      out.write("					<section class=\"section\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<div class=\"table-responsive\">\r\n");
      out.write("									<table class=\"table\" id=\"table1\">\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>Num</th>\r\n");
      out.write("												<th>Name</th>\r\n");
      out.write("												<th>Email</th>\r\n");
      out.write("												<th>Phone</th>\r\n");
      out.write("												<th>City</th>\r\n");
      out.write("												<th>Status</th>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>1</th>\r\n");
      out.write("												<td>김무영</td>\r\n");
      out.write("												<td>vehicula.aliquet@semconsequat.co.uk</td>\r\n");
      out.write("												<td>076 4820 8838</td>\r\n");
      out.write("												<td>Offenburg</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>2</th>\r\n");
      out.write("												<td>이주희</td>\r\n");
      out.write("												<td>fringilla.euismod.enim@quam.ca</td>\r\n");
      out.write("												<td>0500 527693</td>\r\n");
      out.write("												<td>New Quay</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>3</th>\r\n");
      out.write("												<td>윤웅찬</td>\r\n");
      out.write("												<td>mi.Duis@diam.edu</td>\r\n");
      out.write("												<td>(012165) 76278</td>\r\n");
      out.write("												<td>Grumo Appula</td>\r\n");
      out.write("												<td><span class=\"badge bg-danger\">Inactive</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>4</th>\r\n");
      out.write("												<td>이조희</td>\r\n");
      out.write("												<td>velit@nec.com</td>\r\n");
      out.write("												<td>0309 690 7871</td>\r\n");
      out.write("												<td>Ways</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>5</th>\r\n");
      out.write("												<td>Oleg</td>\r\n");
      out.write("												<td>rhoncus.id@Aliquamauctorvelit.net</td>\r\n");
      out.write("												<td>0500 441046</td>\r\n");
      out.write("												<td>Rossignol</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>6</th>\r\n");
      out.write("												<td>Kermit</td>\r\n");
      out.write("												<td>diam.Sed.diam@anteVivamusnon.org</td>\r\n");
      out.write("												<td>(01653) 27844</td>\r\n");
      out.write("												<td>Patna</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>7</th>\r\n");
      out.write("												<td>Jermaine</td>\r\n");
      out.write("												<td>sodales@nuncsit.org</td>\r\n");
      out.write("												<td>0800 528324</td>\r\n");
      out.write("												<td>Mold</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>8</th>\r\n");
      out.write("												<td>Ferdinand</td>\r\n");
      out.write("												<td>gravida.molestie@tinciduntadipiscing.org</td>\r\n");
      out.write("												<td>(016977) 4107</td>\r\n");
      out.write("												<td>Marlborough</td>\r\n");
      out.write("												<td><span class=\"badge bg-danger\">Inactive</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>9</th>\r\n");
      out.write("												<td>Kuame</td>\r\n");
      out.write("												<td>Quisque.purus@mauris.org</td>\r\n");
      out.write("												<td>(0151) 561 8896</td>\r\n");
      out.write("												<td>Tresigallo</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>10</th>\r\n");
      out.write("												<td>Deacon</td>\r\n");
      out.write("												<td>Duis.a.mi@sociisnatoquepenatibus.com</td>\r\n");
      out.write("												<td>07740 599321</td>\r\n");
      out.write("												<td>Karapınar</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>11</th>\r\n");
      out.write("												<td>Channing</td>\r\n");
      out.write("												<td>tempor.bibendum.Donec@ornarelectusante.ca</td>\r\n");
      out.write("												<td>0845 46 49</td>\r\n");
      out.write("												<td>Warrnambool</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>12</th>\r\n");
      out.write("												<td>Aladdin</td>\r\n");
      out.write("												<td>sem.ut@pellentesqueafacilisis.ca</td>\r\n");
      out.write("												<td>0800 1111</td>\r\n");
      out.write("												<td>Bothey</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>13</th>\r\n");
      out.write("												<td>Cruz</td>\r\n");
      out.write("												<td>non@quisturpisvitae.ca</td>\r\n");
      out.write("												<td>07624 944915</td>\r\n");
      out.write("												<td>Shikarpur</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>14</th>\r\n");
      out.write("												<td>Keegan</td>\r\n");
      out.write("												<td>molestie.dapibus@condimentumDonecat.edu</td>\r\n");
      out.write("												<td>0800 200103</td>\r\n");
      out.write("												<td>Assen</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>15</th>\r\n");
      out.write("												<td>Ray</td>\r\n");
      out.write("												<td>placerat.eget@sagittislobortis.edu</td>\r\n");
      out.write("												<td>(0112) 896 6829</td>\r\n");
      out.write("												<td>Hofors</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>16</th>\r\n");
      out.write("												<td>Maxwell</td>\r\n");
      out.write("												<td>diam@dapibus.org</td>\r\n");
      out.write("												<td>0334 836 4028</td>\r\n");
      out.write("												<td>Thane</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>17</th>\r\n");
      out.write("												<td>Carter</td>\r\n");
      out.write("												<td>urna.justo.faucibus@orci.com</td>\r\n");
      out.write("												<td>07079 826350</td>\r\n");
      out.write("												<td>Biez</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>18</th>\r\n");
      out.write("												<td>Stone</td>\r\n");
      out.write("												<td>velit.Aliquam.nisl@sitametrisus.com</td>\r\n");
      out.write("												<td>0800 1111</td>\r\n");
      out.write("												<td>Olivar</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>19</th>\r\n");
      out.write("												<td>Berk</td>\r\n");
      out.write("												<td>fringilla.porttitor.vulputate@taciti.edu</td>\r\n");
      out.write("												<td>(0101) 043 2822</td>\r\n");
      out.write("												<td>Sanquhar</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>20</th>\r\n");
      out.write("												<td>Philip</td>\r\n");
      out.write("												<td>turpis@euenimEtiam.org</td>\r\n");
      out.write("												<td>0500 571108</td>\r\n");
      out.write("												<td>Okara</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>21</th>\r\n");
      out.write("												<td>Kibo</td>\r\n");
      out.write("												<td>feugiat@urnajustofaucibus.co.uk</td>\r\n");
      out.write("												<td>07624 682306</td>\r\n");
      out.write("												<td>La Cisterna</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>22</th>\r\n");
      out.write("												<td>Bruno</td>\r\n");
      out.write("												<td>elit.Etiam.laoreet@luctuslobortisClass.edu</td>\r\n");
      out.write("												<td>07624 869434</td>\r\n");
      out.write("												<td>Rocca d\"Arce</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>23</th>\r\n");
      out.write("												<td>Leonard</td>\r\n");
      out.write("												<td>blandit.enim.consequat@mollislectuspede.net</td>\r\n");
      out.write("												<td>0800 1111</td>\r\n");
      out.write("												<td>Lobbes</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>24</th>\r\n");
      out.write("												<td>Hamilton</td>\r\n");
      out.write("												<td>mauris@diam.org</td>\r\n");
      out.write("												<td>0800 256 8788</td>\r\n");
      out.write("												<td>Sanzeno</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>25</th>\r\n");
      out.write("												<td>Harding</td>\r\n");
      out.write("												<td>Lorem.ipsum.dolor@etnetuset.com</td>\r\n");
      out.write("												<td>0800 1111</td>\r\n");
      out.write("												<td>Obaix</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>26</th>\r\n");
      out.write("												<td>Emmanuel</td>\r\n");
      out.write("												<td>eget.lacus.Mauris@feugiatSednec.org</td>\r\n");
      out.write("												<td>(016977) 8208</td>\r\n");
      out.write("												<td>Saint-Remy-Geest</td>\r\n");
      out.write("												<td><span class=\"badge bg-success\">Active</span></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- footer S -->\r\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/footer.jsp", out, false);
      out.write("\r\n");
      out.write("				<!-- footer E -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- main E -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- app E  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 공통 필요 Script S -->\r\n");
      out.write("	<script src=\"/hotel_prj/admin/assets/static/js/components/dark.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/hotel_prj/admin/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("	<script src=\"/hotel_prj/admin/assets/compiled/js/app.js\"></script>\r\n");
      out.write("	<!-- 공통 필요 Script E -->\r\n");
      out.write("\r\n");
      out.write("	<!--  추가 Script S -->\r\n");
      out.write("	<script src=\"/hotel_prj/admin/assets/extensions/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/hotel_prj/admin/assets/extensions/datatables.net/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/hotel_prj/admin/assets/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("	<script src=\"/hotel_prj/admin/assets/static/js/pages/datatables.js\"></script>\r\n");
      out.write("	<!--  추가 Script E -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
