/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-09 02:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "공지사항";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1716440579524L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("    <meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("    <title>QnA - 자주찾는질문목록 | 엘리시안호텔</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"text/css\" href=\"http://localhost/hotel_prj/static/home/images/ko/pc/common/favicon.ico\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/common_josunhotel.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/contents.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/bluewaves/css/pc/contents.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/swiper.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubPlugin.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubCommon_contents.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubCommon_josunhotel.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/selectbox.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/swiper.min.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/home.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/bluewaves/js/pc/bw_contents.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <noscript>\r\n");
      out.write("        <iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-NP6NJMP\" height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe>\r\n");
      out.write("    </noscript>\r\n");
      out.write("    <div class=\"skip\"><a href=\"#container\">본문 바로가기</a></div>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("		<!--S header  -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<!--E header  -->\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("            $(document).on(\"click\",\".headArea .btnMenu\",function(){\r\n");
      out.write("                if(jQuery(this).hasClass(\"menuOn\")){\r\n");
      out.write("                    var expsrCount = 3;\r\n");
      out.write("                    var $loungeList = jQuery(\".menuDepth-add .gnb-thum li\");\r\n");
      out.write("                    var randomArray = generateRandomNumberArray(expsrCount, $loungeList.length);\r\n");
      out.write("                    $loungeList.addClass(\"hidden\");\r\n");
      out.write("                    $loungeList.each(function(index){\r\n");
      out.write("                        if(randomArray.indexOf(index) > -1){\r\n");
      out.write("                            $(this).removeClass(\"hidden\");\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function(){\r\n");
      out.write("            	//json데이터로 화면구성 --> 임시로 구성해놨음 수정필요!!\r\n");
      out.write("            	$.getJSON('notice.json',function(data){\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            		var noticeList = '';\r\n");
      out.write("            		$.each(data, function(key, value){\r\n");
      out.write("            	          noticeList += '<li>' +\r\n");
      out.write("                          '<div class=\"titArea\">' +\r\n");
      out.write("                              '<strong class=\"listTit\">' + value.category + '</strong>' +\r\n");
      out.write("                              '<span class=\"opValue\">' + value.question + '</span>' +\r\n");
      out.write("                          '</div>' +\r\n");
      out.write("                          '<button type=\"button\" class=\"btnToggle\">' +\r\n");
      out.write("                              '<span class=\"hidden\">상세내용 보기</span>' +\r\n");
      out.write("                          '</button>' +\r\n");
      out.write("                          '<div class=\"toggleCont\">' +\r\n");
      out.write("                              '<div class=\"toggleInner\">' + value.answer + '</div>' +\r\n");
      out.write("                          '</div>' +\r\n");
      out.write("                         '</li>';\r\n");
      out.write("            		});\r\n");
      out.write("                    $('.toggleList').html(noticeList);\r\n");
      out.write("                   \r\n");
      out.write("                    // Toggle 기능 추가\r\n");
      out.write("                    $('.btnToggle').click(function() {\r\n");
      out.write("                        var $toggleCont = $(this).next('.toggleCont');\r\n");
      out.write("                        if ($toggleCont.is(':visible')) {\r\n");
      out.write("                            $toggleCont.slideUp();\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $('.toggleCont').slideUp(); // 다른 열려 있는 답변 닫기\r\n");
      out.write("                            $toggleCont.slideDown();\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("            	});\r\n");
      out.write("            	\r\n");
      out.write("            //상단 카테고리 클릭시 이벤트\r\n");
      out.write("            $(\"#tabArea > li\").click(function(){\r\n");
      out.write("               if(!$(this).hasClass(\"on\")){\r\n");
      out.write("                   $(this).addClass(\"on\");\r\n");
      out.write("                    }\r\n");
      out.write("                \r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            //엔터 이벤트\r\n");
      out.write("            function fncKeyEvent(){\r\n");
      out.write("                if(event.keyCode == 13){\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            //페이지 이동 이벤트\r\n");
      out.write("            function fncPage(page){\r\n");
      out.write("              \r\n");
      out.write("            }\r\n");
      out.write("            //검색 이벤트\r\n");
      out.write("            function fncSearch() {\r\n");
      out.write("               	\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        <form action=\"/customer/faq.do\" method=\"get\" id=\"form\">\r\n");
      out.write("            <input type=\"hidden\" name=\"_method\" id=\"_method\">\r\n");
      out.write("            <input type=\"hidden\" value=\"253105\" name=\"bbsMstrSn\">\r\n");
      out.write("            <input type=\"hidden\" name=\"bbsSn\" id=\"bbsSn\">\r\n");
      out.write("            <input type=\"hidden\" name=\"deleteYn\" id=\"deleteYn\" value=\"N\">\r\n");
      out.write("            <input type=\"hidden\" name=\"page\" id=\"page\" value=\"1\">\r\n");
      out.write("            <input type=\"hidden\" name=\"searchDataType\" value=\"77\">\r\n");
      out.write("            <div id=\"container\" class=\"container mypage ctmService\">\r\n");
      out.write("                <h1 class=\"hidden\">고객센터</h1>\r\n");
      out.write("                <div class=\"topArea\">\r\n");
      out.write("                    <div class=\"topInner\">\r\n");
      out.write("                        <h2 class=\"titDep1\">Customer Service</h2>\r\n");
      out.write("                        <p class=\"pageGuide\">호텔 이용과 관련된 궁금한 사항을 남겨주시면 신속하게 답변 드리겠습니다.<br>항상 고객의 소리에 귀 기울이는 조선호텔앤리조트가 되겠습니다.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                    <div class=\"lnbArea\">\r\n");
      out.write("                        <ul class=\"lnb ctmType\">\r\n");
      out.write("                            <li><a href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("                            <li class=\"on\"><a href=\"#none\">FAQ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"myContents\">\r\n");
      out.write("                        <h3 class=\"titDep2\">FAQ</h3>\r\n");
      out.write("                        <h4 class=\"titDep3 hidden\">FAQ</h4>\r\n");
      out.write("                        <div class=\"searchBox\">\r\n");
      out.write("                            <div class=\"searchOp\">\r\n");
      out.write("                                <span class=\"hidden\">검색</span>\r\n");
      out.write("                                <div class=\"selectWrap\" style=\"width:220px\">\r\n");
      out.write("                                    <select name=\"searchCtgry\" id=\"searchCtgry\" class=\"form-control\" style=\"height:150px;\">\r\n");
      out.write("                                        <option value=\"\">전체</option>\r\n");
      out.write("                                        <option value=\"F01\">멤버십 계정</option>\r\n");
      out.write("                                        <option value=\"F02\">카드</option>\r\n");
      out.write("                                        <option value=\"F03\">포인트</option>\r\n");
      out.write("                                        <option value=\"F04\">전환회원</option>\r\n");
      out.write("                                        <option value=\"F05\">바우처</option>\r\n");
      out.write("                                        <option value=\"F06\">기타</option>\r\n");
      out.write("                                    </select> \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"intWord\">\r\n");
      out.write("                                    <span class=\"intArea\">\r\n");
      out.write("                                        <input type=\"text\" id=\"searchDataValue\" name=\"searchDataValue\" style=\"width:675px\" title=\"검색어 입력\" placeholder=\"검색어를 입력해주세요.\" onkeypress=\"fncKeyEvent();\" value=\"\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>                     \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"btnWrap\">\r\n");
      out.write("                                <a href=\"#search\" class=\"btnSC btnM\" role=\"button\" onclick=\"fncSearch(); return false;\">검색</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"tabType01 tabType02 tabToggle\" id=\"tabArea\">\r\n");
      out.write("                            <li id=\"F00\" class=\"on\"><a href=\"#tab01-F00\">전체</a></li>\r\n");
      out.write("                            <li id=\"F01\"><a href=\"#tab01-F01\">멤버십 계정</a></li>\r\n");
      out.write("                            <li id=\"F02\"><a href=\"#tab01-F02\">카드</a></li>\r\n");
      out.write("                            <li id=\"F03\"><a href=\"#tab01-F03\">포인트</a></li>\r\n");
      out.write("                            <li id=\"F04\"><a href=\"#tab01-F04\">전환회원</a></li>\r\n");
      out.write("                            <li id=\"F05\"><a href=\"#tab01-F05\">바우처</a></li>\r\n");
      out.write("                            <li id=\"F06\"><a href=\"#tab01-F06\">기타</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div id=\"tab01-F00\" class=\"tabCont\" style=\"display:block\">\r\n");
      out.write("                            <h3 class=\"hidden\">전체</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F01\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">멤버십 계정</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\">\r\n");
      out.write("                                \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F02\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">카드</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\"></ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F03\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">포인트</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\"></ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F04\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">전환회원</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F05\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">바우처</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\">\r\n");
      out.write("                                \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"tab01-F06\" class=\"tabCont\">\r\n");
      out.write("                            <h3 class=\"hidden\">기타</h3>\r\n");
      out.write("                            <div class=\"tabFaqType\">\r\n");
      out.write("                                <ul class=\"toggleList rsvList\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pagination\">\r\n");
      out.write("                            <span class=\"current\"><span class=\"hidden\">현재페이지</span>1</span>\r\n");
      out.write("                            <a href=\"javascript:fncPage(2);\">2</a>\r\n");
      out.write("                            <a href=\"javascript:fncPage(3);\">3</a>\r\n");
      out.write("                            <a href=\"javascript:fncPage(4);\">4</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      \r\n");
      out.write("<!--S footer  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!--E footer  -->\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
