/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-10 15:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.asd.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.DAO.BoardDetailDAO;
import java.io.Console;
import oracle.net.aso.b;
import oracle.net.aso.q;
import VO.BoardVO;
import java.util.List;
import user.DAO.BoardDAO;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1715750612809L));
    _jspx_dependants.put("jar:file:/C:/E/dev/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/theater_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("oracle.net.aso.b");
    _jspx_imports_classes.add("user.DAO.BoardDAO");
    _jspx_imports_classes.add("user.DAO.BoardDetailDAO");
    _jspx_imports_classes.add("java.io.Console");
    _jspx_imports_classes.add("oracle.net.aso.q");
    _jspx_imports_classes.add("VO.BoardVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"-1\" />\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"No-Cache\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<meta id=\"ctl00_og_title\" property=\"og:title\" content=\"무비차트 &lt; 무비차트 | 영화 그 이상의 감동. CGV\"></meta>\r\n");
      out.write("<!-- 공지사항 css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/notice.css\">\r\n");
      out.write("<meta id=\"ctl00_og_image\" property=\"og:image\" content=\"https://img.cgv.co.kr/WebApp/images/common/logo_new_kakao_prevw.png\"></meta>\r\n");
      out.write("<link rel=\"alternate\" href=\"http://m.cgv.co.kr\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<title id=\"ctl00_headerTitle\">공지/뉴스, 자주찾는질문 | 명화 그 이상의 감동. 띵화관</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/images/favicon.ico\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/webfont.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/reset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"../css/layout.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/module.css?20211209\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/content.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/common.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/eggupdate.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"print\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/print.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/js/jquery.ui/smoothness/jquery-ui-1.10.4.custom.min.css\" />\r\n");
      out.write("<title id=\"ctl00_headerTitle\">공지/뉴스, 자주찾는질문 | 명화 그 이상의 감동. 띵화관</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/images/favicon.ico\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/webfont.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/reset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"../css/layout.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/module.css?20211209\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/content.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/common.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/eggupdate.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"print\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/css/print.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://img.cgv.co.kr/R2014/js/jquery.ui/smoothness/jquery-ui-1.10.4.custom.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.config.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.tmpl.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquerlocal.adguardy.plugin/jquery.paging.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.ui/jquery-ui-1.10.4.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.utils.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.utils.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.utils.pageing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.init.js\"></script>\r\n");
      out.write("<!--[if lte IE 9]><script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.placeholder.js\"></script><![endif]-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.dotdotdot.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/silverlight_link.js\"></script>\r\n");
      out.write("<script src=\"https://img.cgv.co.kr/R2014/js/slick/slick.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/phototicket/phototicket.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/slick.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/slick-theme-custom.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/icheck/login.timer.js\"></script>\r\n");
      out.write("<script src=\"https://img.cgv.co.kr/R2014/js/icheck/icheck.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/js/icheck/iCheck.css\" />\r\n");
      out.write("<!-- 홈페이지 CSS 일원화로 인한 반영 20220721 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.cgv.co.kr/resource_pc/css/cgv.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/resource_pc/js/cgvUi.js\"></script>\r\n");
      out.write("<!-- 각페이지 Header Start-->\r\n");
      out.write("<!--jQuery CDN ����-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--jQuery CDN ��-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"http://img.cgv.co.kr/R2014/css/customer.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- header start -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- header end -->\r\n");
      out.write("\r\n");
      out.write("	<div id=\"cgvwrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- SearchVO 빈에 등록 -->\r\n");
      out.write("		");
      VO.SearchVO sVO = null;
      sVO = (VO.SearchVO) _jspx_page_context.getAttribute("sVO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (sVO == null){
        sVO = new VO.SearchVO();
        _jspx_page_context.setAttribute("sVO", sVO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("sVO"), request);
      out.write("\r\n");
      out.write("		");

		String FAQS = request.getParameter("FAQS");
		//FAQS에 따른 공지뉴스/자주찾는질문 변수설정
		String qaChg = FAQS.equals("Q") ? "on" : "";
		String noticeChg = FAQS.equals("N") ? "on" : "";
		String faqsTitle = FAQS.equals("Q") ? "자주찾는 질문" : "공지/뉴스";
		String faqsContent = "";
		if(faqsTitle.equals("자주찾는 질문")){
			faqsContent = "회원님들께서 가장 자주하시는 질문을 모았습니다. <br />궁금하신 내용에 대해 검색해보세요.";
		}else{
			faqsContent ="명화관의 공지사항들을 모았습니다. <br />궁금하신 내용에 대해 검색해보세요.";
		}
		
		BoardDAO bDAO = BoardDAO.getInstance();

		//카테고리의 리스트
		List<String> faqsList = bDAO.selectCategory(FAQS);

		////////페이지 수 설정////////////

		//1.총 레코드의 수 얻기
		int totalCount = bDAO.selectTotalCount(FAQS);
		//2.한 화면에 보여줄 게시물의 수
		int pageScale = 10;
		//3. 총 페이지수
		int totalPage = (int) Math.ceil((double) totalCount / pageScale);
		//4. 게시물의 시작 번호
		String tempPage = sVO.getCurrentPage();
		int currentPage = 1;
		if (tempPage != null) {
			try {
				currentPage = Integer.parseInt(tempPage);
			} catch (NumberFormatException nfe) {
				nfe.printStackTrace();
			}
		} //end if	
		int startNum = currentPage * pageScale - pageScale + 1;
		//5.끝번호
		int endNum = startNum + pageScale - 1;

		//6.
		sVO.setStartNum(startNum);
		sVO.setEndNum(endNum);

		List<BoardVO> list = bDAO.selectBoard(startNum, endNum, FAQS);
		pageContext.setAttribute("list", list);
		pageContext.setAttribute("totalCount", totalCount);
		pageContext.setAttribute("pageScale", pageScale);
		pageContext.setAttribute("currentPage", currentPage);
		
      out.write("\r\n");
      out.write("		<!-- Contaniner -->\r\n");
      out.write("		<div id=\"contaniner\" class=\"\">\r\n");
      out.write("			<!-- 벽돌 배경이미지 사용 시 class=\"bg-bricks\" 적용 / 배경이미지가 없을 경우 class 삭제  -->\r\n");
      out.write("			<!-- Contents Area -->\r\n");
      out.write("			<div id=\"contents\">\r\n");
      out.write("				<!-- Contents Start -->\r\n");
      out.write("				<div class=\"cols-content\">\r\n");
      out.write("					<div class=\"col-aside\">\r\n");
      out.write("						<h2>고객센터 메뉴</h2>\r\n");
      out.write("						<div class=\"snb\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class='");
      out.print(qaChg);
      out.write("'><a\r\n");
      out.write("									href=\"http://localhost/theater_prj/asd/jsp/board.jsp?FAQS=Q\">자주찾는\r\n");
      out.write("										질문<i></i>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li class='");
      out.print(noticeChg);
      out.write("'><a\r\n");
      out.write("									href=\"http://localhost/theater_prj/asd/jsp/board.jsp?FAQS=N\">공지/뉴스<i></i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-detail\">\r\n");
      out.write("						<div class=\"customer_top\">\r\n");
      out.write("							<h2 class=\"tit\" style=\"text-align: left;\">");
      out.print(faqsTitle);
      out.write("</h2>\r\n");
      out.write("							<p class=\"stit\">");
      out.print(faqsContent );
      out.write("</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_area\">\r\n");
      out.write("							<legend>\r\n");
      out.write("								<label for=\"searchtext\">검색</label>\r\n");
      out.write("							</legend>\r\n");
      out.write("							<input id=\"searchtext\" type=\"text\" class=\"c_input\" title=\"검색어 입력\"\r\n");
      out.write("								placeholder=\"검색어를 입력해 주세요\" value=\"\" style=\"width: 275px;\" />\r\n");
      out.write("							<button type=\"button\" class=\"round inblack\" title=\"검색하기\"\r\n");
      out.write("								id=\"btn_search\" onclick=\"searchContent(");
      out.print(startNum);
      out.write(',');
      out.print(endNum);
      out.write(',');
      out.write('\'');
      out.print(FAQS);
      out.write('\'');
      out.write(',');
      out.print(currentPage);
      out.write(")\">\r\n");
      out.write("								<span>검색하기</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<script>\r\n");
      out.write("							function navigateWithFAQS(menu, value) {\r\n");
      out.write("								// FAQSInput 요소를 찾아 FAQS 값을 변경\r\n");
      out.write("								document.getElementById('FAQSInput').value = value;\r\n");
      out.write("						\r\n");
      out.write("								// 현재 위치로 이동\r\n");
      out.write("								window.location.href = '/board.jsp';\r\n");
      out.write("							}\r\n");
      out.write("						</script>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"c_tab_wrap\">\r\n");
      out.write("							<ul class=\"c_tab type_free\">\r\n");
      out.write("								<li class='on' id=\"allcategory\"><a\r\n");
      out.write("									href=\"javascript:void(0);\" style=\"font-size: 11px;\"\r\n");
      out.write("									title=\"선택된 탭메뉴\"\r\n");
      out.write("									onclick=\"location.reload();\">전체</a></li>\r\n");
      out.write("								");

								for (String category : faqsList) {
								
      out.write("\r\n");
      out.write("								<li id=\"");
      out.print(category);
      out.write("\"><a href=\"javascript:void(0);\"\r\n");
      out.write("									style=\"font-size: 11px;\"\r\n");
      out.write("									onclick=\"selectCategory(");
      out.print(startNum);
      out.write(',');
      out.print(endNum);
      out.write(',');
      out.write('\'');
      out.print(FAQS);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(category);
      out.write('\'');
      out.write(',');
      out.print(currentPage);
      out.write(")\">\r\n");
      out.write("										");
      out.print(category);
      out.write("\r\n");
      out.write("								</a></li>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"search_result\">\r\n");
      out.write("							<span id=\"totalSearchCnt\" class=\"num\">");
      out.print(totalCount);
      out.write("건 이\r\n");
      out.write("								검색되었습니다.</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tbl_area\">\r\n");
      out.write("							<table cellspacing=\"0\" cellpadding=\"0\" class=\"tbl_notice_list\">\r\n");
      out.write("								<caption>목록</caption>\r\n");
      out.write("								<colgroup>\r\n");
      out.write("									<col style=\"width: 70px;\" />\r\n");
      out.write("									<col style=\"width: 160px;\" />\r\n");
      out.write("									<col style=\"\" />\r\n");
      out.write("									<col style=\"width: 140px;\" />\r\n");
      out.write("									<col style=\"width: 120px\" />\r\n");
      out.write("								</colgroup>\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">번호</th>\r\n");
      out.write("										<th scope=\"col\">구분</th>\r\n");
      out.write("										<th scope=\"col\" class=\"tit\" style=\"text-align: center\">제목</th>\r\n");
      out.write("										<th scope=\"col\">등록일</th>\r\n");
      out.write("										<th scope=\"col\">조회수</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody id=\"boardTable\">\r\n");
      out.write("									");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /asd/jsp/board.jsp(261,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("board");
        // /asd/jsp/board.jsp(261,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /asd/jsp/board.jsp(261,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVarStatus("i");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("										<tr>\r\n");
              out.write("											<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount-(currentPage-1)*pageScale-i.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("											<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("											<td id=\"title0\"  style=\"text-align: center\" class=\"txt\"><a href=\"boardDetail.jsp?FAQS=");
              out.print(FAQS);
              out.write("&boardNumber=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" \r\n");
              out.write("												onclick=\"addViews(");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(')');
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</a></td>\r\n");
              out.write("											<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardInputDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("											<td class=\"num\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardViews}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("										</tr>\r\n");
              out.write("									");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("						<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");
      out.write("						<div class=\"paging\" id=\"paging\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								");

								for (int i = 1; i <= totalPage; i++) {
								
      out.write("\r\n");
      out.write("								<li><a href=\"board.jsp?FAQS=");
      out.print(FAQS);
      out.write("&currentPage=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("							<a href=\"board.jsp?FAQS=");
      out.print(FAQS);
      out.write("&currentPage=");
      out.print(currentPage+1);
      out.write("\"><button class=\"btn-paging end\" type=\"button\" onclick=\"\">끝</button></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //Contents End -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- S 예매하기 및 TOP Fixed 버튼 -->\r\n");
      out.write("		<div class=\"fixedBtn_wrap\">\r\n");
      out.write("\r\n");
      out.write("			<a href=\"/ticket/\" class=\"btn_fixedTicketing\">예매하기</a> <a\r\n");
      out.write("				href=\"#none\" class=\"btn_gotoTop\"><img\r\n");
      out.write("				src=\"https://img.cgv.co.kr/R2014/images/common/btn/gotoTop.png\"\r\n");
      out.write("				alt=\"최상단으로 이동\" /></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- E 예매하기 및 TOP Fixed 버튼 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- S Footer -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- S Footer -->\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function addViews(boardNumber) {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '/theater_prj/BoardViewServlet',\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        data: {\r\n");
      out.write("            boardNumber: boardNumber\r\n");
      out.write("        },\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr) {\r\n");
      out.write("            alert(xhr.status);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("///////////////////////////////< BoardCategoryServlet ajax연결 >//////////////////////////////////////\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("/*\r\n");
      out.write("    카테고리를 클릭했을 때 해당 카테고리의 게시물을 로드하는 함수\r\n");
      out.write("    */\r\n");
      out.write("    function selectCategory(startNum, endNum ,FAQS,categoryId,currentPage) {\r\n");
      out.write("    	//카테고리 색상변경 함수 	\r\n");
      out.write("    	changColorCategory(categoryId);\r\n");
      out.write("    	\r\n");
      out.write("        //ajax에서 json처리할 데이터 모음\r\n");
      out.write("    	var param={\r\n");
      out.write("                startNum: 1, // 시작 번호\r\n");
      out.write("                endNum: 10, // 종료 번호\r\n");
      out.write("                FAQS: FAQS,\r\n");
      out.write("                category: categoryId, // 카테고리 ID를 서버에 전달\r\n");
      out.write("                currentPage: currentPage\r\n");
      out.write("            };\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            url: '/theater_prj/BoardCategoryServlet', // 해당 카테고리 게시물을 가져오는 서블릿 URL\r\n");
      out.write("            data : param ,\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("            	\r\n");
      out.write("                //  테이블에 데이터를 표시하는 함수\r\n");
      out.write("                displayData(response);\r\n");
      out.write("                //  카테고리 클릭시 페이지 비동기 함수\r\n");
      out.write("                displayPagination(response);\r\n");
      out.write("		    	//총 검색 count 비동기 함수\r\n");
      out.write("    			searchTotalBoard(response);\r\n");
      out.write("                                \r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                console.error('Error:', error);\r\n");
      out.write("            }\r\n");
      out.write("        });//end ajax\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("    테이블에 데이터를 표시하는 함수\r\n");
      out.write("    */\r\n");
      out.write("    function displayData(response) {\r\n");
      out.write("    	var table = document.getElementById(\"boardTable\");\r\n");
      out.write("		table.innerHTML= \"\";	\r\n");
      out.write("		\r\n");
      out.write("		var object = JSON.parse(response);\r\n");
      out.write("		var url = \"\";\r\n");
      out.write("		var result = object.result;\r\n");
      out.write("		var categorycount = object.Categorycount;\r\n");
      out.write("		var currentPage = object.currentPage;\r\n");
      out.write("		var pageScale = 10;\r\n");
      out.write("		for(var i=0 ; i < result.length; i++){\r\n");
      out.write("			\r\n");
      out.write("			var row = table.insertRow(i); // 행 추가\r\n");
      out.write("				//a태그 링크 생성\r\n");
      out.write("				url = \"boardDetail.jsp?FAQS=\" +object.FAQS + \"&boardNumber=\" + result[i].boardNumber;\r\n");
      out.write("				\r\n");
      out.write("		        // 각 속성에 대한 열 추가\r\n");
      out.write("		        var cell1 = row.insertCell(0);\r\n");
      out.write("		        var cell2 = row.insertCell(1);\r\n");
      out.write("		        var cell3 = row.insertCell(2);\r\n");
      out.write("		        var cell4 = row.insertCell(3);\r\n");
      out.write("		        var cell5 = row.insertCell(4);\r\n");
      out.write("\r\n");
      out.write("		        // 각 열에 데이터 입력\r\n");
      out.write("		        cell1.innerHTML = categorycount-(currentPage-1)*pageScale-i;\r\n");
      out.write("		        cell2.innerHTML = result[i].categoryName;\r\n");
      out.write("		        cell3.innerHTML = '<a href=\"' + url + '\">' + result[i].boardTitle + '</a>';\r\n");
      out.write("		        cell4.innerHTML = result[i].boardInputDate;\r\n");
      out.write("		        cell5.innerHTML = result[i].boardViews;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("  		\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /*\r\n");
      out.write("    카테고리 클릭시 페이지네이션 비동기 처리\r\n");
      out.write("    */ \r\n");
      out.write("    function displayPagination(response) {\r\n");
      out.write("    	var paging = document.getElementById(\"paging\");\r\n");
      out.write("        paging.innerHTML= \"\";	\r\n");
      out.write("      	\r\n");
      out.write("        \r\n");
      out.write("        var object = JSON.parse(response);\r\n");
      out.write("		var totalPage = object.totalPage;\r\n");
      out.write("		var categoryId = object.category;\r\n");
      out.write("		var FAQS = object.FAQS;\r\n");
      out.write("		var currentPage = object.currentPage;\r\n");
      out.write("		\r\n");
      out.write("		var paginationList = document.createElement(\"ul\");\r\n");
      out.write("		    for (var i = 1; i <= totalPage; i++) {\r\n");
      out.write("		        var listItem = document.createElement(\"li\");\r\n");
      out.write("		        var link = document.createElement(\"a\");\r\n");
      out.write("		     	link.href = \"javascript:void(0);\";     \r\n");
      out.write("		     	 link.textContent = i;\r\n");
      out.write("		         link.onclick = function () {\r\n");
      out.write("		         var pageNumber = this.textContent;\r\n");
      out.write("		         selectPagingCategory(FAQS, categoryId, pageNumber);\r\n");
      out.write("		         };\r\n");
      out.write("		        listItem.appendChild(link);\r\n");
      out.write("		        paginationList.appendChild(listItem);\r\n");
      out.write("		    }\r\n");
      out.write("		    // 페이지네이션 요소에 추가\r\n");
      out.write("		    paging.appendChild(paginationList);\r\n");
      out.write("			\r\n");
      out.write("		    var endButton = document.createElement(\"button\");\r\n");
      out.write("		    endButton.classList.add(\"btn-paging\", \"end\");\r\n");
      out.write("		    endButton.type = \"button\";\r\n");
      out.write("		    endButton.textContent = \"끝\";\r\n");
      out.write("		    \r\n");
      out.write("		    endButton.onclick = function () {\r\n");
      out.write("		    	endButton.href=\"javascript:void(0);\";\r\n");
      out.write("		        var nextPage = currentPage + 1;\r\n");
      out.write("		        selectPagingCategory(FAQS, categoryId, nextPage);\r\n");
      out.write("		    };\r\n");
      out.write("		    paging.appendChild(endButton);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  	/*\r\n");
      out.write("  	카테고리 선택 후 로딩된 페이지 클릭 시 처리 함수\r\n");
      out.write("  	*/\r\n");
      out.write("  	function selectPagingCategory(FAQS, categoryId, pageNumber) {\r\n");
      out.write("  		\r\n");
      out.write("		var	startNum = (pageNumber - 1) * 10 + 1;\r\n");
      out.write("		var	endNum = pageNumber * 10; \r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  	    //ajax에서 json처리할 데이터 모음\r\n");
      out.write("  	    var param = {\r\n");
      out.write("  	    	startNum: startNum,\r\n");
      out.write("  	    	endNum: endNum,\r\n");
      out.write("  	        FAQS: FAQS,\r\n");
      out.write("  	        category: categoryId, \r\n");
      out.write("  	    }\r\n");
      out.write("  	   \r\n");
      out.write("		$.ajax({\r\n");
      out.write("  	        type: 'POST',\r\n");
      out.write("  	        url: '/theater_prj/BoardCategoryServlet', // 해당 카테고리 게시물을 가져오는 서블릿 URL\r\n");
      out.write("  	        data: param,\r\n");
      out.write("  	        success: function (response) {\r\n");
      out.write("  	            // 받은 JSON 데이터를 파싱하여 테이블에 표시\r\n");
      out.write("  	            var data = JSON.parse(response);\r\n");
      out.write("  	            //  테이블에 데이터를 표시하는 함수\r\n");
      out.write("  	            displayData(response);\r\n");
      out.write("  	            \r\n");
      out.write("  	           \r\n");
      out.write("  	        },\r\n");
      out.write("  	        error: function (xhr, status, error) {\r\n");
      out.write("  	            console.error('Error:', error);\r\n");
      out.write("  	        }\r\n");
      out.write("  	    });//end ajax\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("    /*\r\n");
      out.write("    카테고리 클릭시 색상 변경 함수\r\n");
      out.write("    */\r\n");
      out.write("    function changColorCategory(categoryId){\r\n");
      out.write("    	\r\n");
      out.write("	if(categoryId == null){\r\n");
      out.write("    var clickedElement = document.getElementById(\"allcategory\");\r\n");
      out.write("	clickedElement.className = 'on';\r\n");
      out.write("    var allCategoryElements = document.querySelectorAll('.c_tab.type_free li');\r\n");
      out.write("    for (var i = 0; i < allCategoryElements.length; i++) {\r\n");
      out.write("        if (allCategoryElements[i] !== clickedElement) {\r\n");
      out.write("        	allCategoryElements[i].classList.remove('on');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("	}else{\r\n");
      out.write("	var clickedElement = document.getElementById(categoryId);\r\n");
      out.write("	clickedElement.className = 'on';\r\n");
      out.write("	 // 나머지 카테고리의 클래스 제거\r\n");
      out.write("    var allCategoryElements = document.querySelectorAll('.c_tab.type_free li');\r\n");
      out.write("    for (var i = 0; i < allCategoryElements.length; i++) {\r\n");
      out.write("        if (allCategoryElements[i] !== clickedElement) {\r\n");
      out.write("        	allCategoryElements[i].classList.remove('on');\r\n");
      out.write("        	}\r\n");
      out.write("    	}\r\n");
      out.write("	}	\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write(" 	/*\r\n");
      out.write(" 	게시물 검색 수 비동기 처리\r\n");
      out.write(" 	*/\r\n");
      out.write("  	function searchTotalBoard(response){\r\n");
      out.write(" 		var countLable = document.getElementById(\"totalSearchCnt\");\r\n");
      out.write(" 		countLable.innerHTML=\"\";\r\n");
      out.write(" 		\r\n");
      out.write("        var object = JSON.parse(response);\r\n");
      out.write("		var count = object.Categorycount;\r\n");
      out.write("		\r\n");
      out.write("		countLable.innerHTML = count + '건 이 검색되었습니다.';\r\n");
      out.write("		\r\n");
      out.write(" 	}\r\n");
      out.write("    \r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////  \r\n");
      out.write("///////////////////////////////< BoardSearchServlet  ajax연결 >//////////////////////////////////////\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("	검색어 검색후 해당 게시물 로드한함수\r\n");
      out.write("	*/\r\n");
      out.write("	\r\n");
      out.write("	function searchContent(startNum,endNum,FAQS,currentPage){\r\n");
      out.write("		var text = document.getElementById(\"searchtext\").value;\r\n");
      out.write("		if(text===\"\"){\r\n");
      out.write("			alert(\"검색어를 입력해 주십시오\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		var param={\r\n");
      out.write("			startNum: 1,\r\n");
      out.write("			endNum: 10,\r\n");
      out.write("			text : text,\r\n");
      out.write("			FAQS : FAQS,\r\n");
      out.write("			currentPage : currentPage\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: 'POST',\r\n");
      out.write("			url: '/theater_prj/BoardSearchServlet',\r\n");
      out.write("			data : param,\r\n");
      out.write("			success: function(response){\r\n");
      out.write("				var object = JSON.parse(response);\r\n");
      out.write("				var isEmpty = object.searchTextExists;\r\n");
      out.write("				if(isEmpty){\r\n");
      out.write("					alert(\"해당하는 제목이 없습니다.\")\r\n");
      out.write("					document.getElementById(\"searchtext\").value = \"\"; // 검색어를 비웁니다.\r\n");
      out.write("					document.getElementById(\"searchtext\").focus(); //포커스주기\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				//카테고리 색깔 제거\r\n");
      out.write("				var allCategoryElements = document.querySelectorAll('.c_tab.type_free li');\r\n");
      out.write("				allCategoryElements.forEach(function(element) {\r\n");
      out.write("   				 element.classList.remove('on');\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				//  테이블에 데이터를 표시하는 함수\r\n");
      out.write("                displayData(response);\r\n");
      out.write("                //  카테고리 클릭시 페이지 비동기 함수\r\n");
      out.write("                displaySearchPagination(response);\r\n");
      out.write("		    	//총 검색 count 비동기 함수\r\n");
      out.write("    			searchTotalBoard(response);\r\n");
      out.write("		    	\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xhr, status, error){\r\n");
      out.write("				alert(\"오류발생\");\r\n");
      out.write("				console.error('Error:', error);\r\n");
      out.write("			}\r\n");
      out.write("		})//end ajax\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	 /*\r\n");
      out.write("    검색후 페이지네이션 비동기 처리\r\n");
      out.write("    */ \r\n");
      out.write("    function displaySearchPagination(response) {\r\n");
      out.write("    	var paging = document.getElementById(\"paging\");\r\n");
      out.write("        paging.innerHTML= \"\";	\r\n");
      out.write("      	\r\n");
      out.write("        var object = JSON.parse(response);\r\n");
      out.write("		var totalPage = object.totalPage;\r\n");
      out.write("		var FAQS = object.FAQS;\r\n");
      out.write("        var searchText = object.searchText;\r\n");
      out.write("        var currentPage = object.currentPage;\r\n");
      out.write("        \r\n");
      out.write("		var paginationList = document.createElement(\"ul\");\r\n");
      out.write("		    for (var i = 1; i <= totalPage; i++) {\r\n");
      out.write("		        var listItem = document.createElement(\"li\");\r\n");
      out.write("		        var link = document.createElement(\"a\");\r\n");
      out.write("		     	link.href = \"javascript:void(0);\";     \r\n");
      out.write("		     	 link.textContent = i;\r\n");
      out.write("		         link.onclick = function () {\r\n");
      out.write("		         var pageNumber = this.textContent;\r\n");
      out.write("		         selectSearchPagingCategory(FAQS, searchText, pageNumber);\r\n");
      out.write("		         };\r\n");
      out.write("		        listItem.appendChild(link);\r\n");
      out.write("		        paginationList.appendChild(listItem);\r\n");
      out.write("		    }\r\n");
      out.write("		    // 페이지네이션 요소에 추가\r\n");
      out.write("		    paging.appendChild(paginationList);\r\n");
      out.write("\r\n");
      out.write("		    var endButton = document.createElement(\"button\");\r\n");
      out.write("		    endButton.classList.add(\"btn-paging\", \"end\");\r\n");
      out.write("		    endButton.type = \"button\";\r\n");
      out.write("		    endButton.textContent = \"끝\";\r\n");
      out.write("		    // endButton.onclick에 필요한 동작을 추가하세요\r\n");
      out.write("		    endButton.onclick = function () {\r\n");
      out.write("		    endButton.href=\"javascript:void(0);\";\r\n");
      out.write("		       var nextPage = currentPage + 1;\r\n");
      out.write("		       selectSearchPagingCategory(FAQS, searchText, nextPage);\r\n");
      out.write("		    };\r\n");
      out.write("		    paging.appendChild(endButton);\r\n");
      out.write("		\r\n");
      out.write("    }\r\n");
      out.write("    /*\r\n");
      out.write("    검색후 클릭시 페이지네이션 비동기 처리\r\n");
      out.write("    */ 	 \r\n");
      out.write("	function selectSearchPagingCategory(FAQS, searchText, pageNumber) {\r\n");
      out.write("		var	startNum = (pageNumber - 1) * 10 + 1;\r\n");
      out.write("		var	endNum = pageNumber * 10; \r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  	    //ajax에서 json처리할 데이터 모음\r\n");
      out.write("  	    var param = {\r\n");
      out.write("  	    	startNum: startNum,\r\n");
      out.write("  	    	endNum: endNum,\r\n");
      out.write("  	        FAQS: FAQS,\r\n");
      out.write("  	     	text: searchText, \r\n");
      out.write("  	     	currentPage: pageNumber\r\n");
      out.write("  	    }\r\n");
      out.write("  	   \r\n");
      out.write("		$.ajax({\r\n");
      out.write("  	        type: 'POST',\r\n");
      out.write("  	        url: '/theater_prj/BoardSearchServlet', // 해당 카테고리 게시물을 가져오는 서블릿 URL\r\n");
      out.write("  	        data: param,\r\n");
      out.write("  	        success: function (response) {\r\n");
      out.write("  	            // 받은 JSON 데이터를 파싱하여 테이블에 표시\r\n");
      out.write("  	            var data = JSON.parse(response);\r\n");
      out.write("  	            //  테이블에 데이터를 표시하는 함수\r\n");
      out.write("  	            displayData(response);\r\n");
      out.write("  	            \r\n");
      out.write("  	           \r\n");
      out.write("  	        },\r\n");
      out.write("  	        error: function (xhr, status, error) {\r\n");
      out.write("  	            console.error('Error:', error);\r\n");
      out.write("  	        }\r\n");
      out.write("  	    });//end ajax\r\n");
      out.write("  	}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
