/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-22 09:43:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.asd.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.VO.UserVO;
import admin.AdminVO;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("user.VO.UserVO");
    _jspx_imports_classes.add("admin.AdminVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!--bootstrap 시작-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--bootstrap 끝-->\r\n");
      out.write("<!--jQeury CDN 시작-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--jQeury CDN 끝-->\r\n");
      out.write("    <meta id=\"ctl00_og_image\" property=\"og:image\" content=\"https://img.cgv.co.kr/WebApp/images/common/logo_new_kakao_prevw.png\"></meta>\r\n");
      out.write("    <link rel=\"alternate\" href=\"http://m.cgv.co.kr\" />\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <title id=\"ctl00_headerTitle\">로그인 | 명화 그 이상의 감동. 띵화관</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://img.cgv.co.kr/R2014/images/favicon.ico\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/webfont.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"../css/layout.css\" />\r\n");
      out.write("     <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"../css/module.css\" /> \r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/content.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/common.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/eggupdate.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"print\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/print.css\" />    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/js/jquery.ui/smoothness/jquery-ui-1.10.4.custom.min.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"/common/js/extraTheaters.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.config.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.tmpl.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.validate.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.paging.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.ui/jquery-ui-1.10.4.custom.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.utils.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.utils.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.utils.pageing.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/app.init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--[if lte IE 9]><script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.placeholder.js\"></script><![endif]-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.dotdotdot.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/silverlight_link.js\"></script>\r\n");
      out.write("	<script src=\"https://img.cgv.co.kr/R2014/js/slick/slick.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/phototicket/phototicket.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/slick.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/slick-theme-custom.css\" />\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/R2014/js/icheck/login.timer.js\"></script>\r\n");
      out.write("    <script src=\"https://img.cgv.co.kr/R2014/js/icheck/icheck.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/js/icheck/iCheck.css\" />\r\n");
      out.write("\r\n");
      out.write("	<!-- 2020.05.07 감정지수/프리에그 프로젝트 추가 -->\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"all\" type=\"text/css\" href=\"https://img.cgv.co.kr/R2014/css/preegg.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 홈페이지 CSS 일원화로 인한 반영 20220721 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://img.cgv.co.kr/resource_pc/css/cgv.min.css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://img.cgv.co.kr/resource_pc/js/cgvUi.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 로그인 */\r\n");
      out.write(".wrap-login{ width: 980px; position:relative;padding:30px 30px 0;}\r\n");
      out.write(".wrap-login h3{height:auto;margin:0;background:none;line-height:1.2;text-align:left; color:#222222; font-size:15px;}\r\n");
      out.write(".wrap-login h3 >  strong{ color:#fb4357;}\r\n");
      out.write(".sect-login{ width:541px; }\r\n");
      out.write(".wrap-login .tab-menu-round > li{ width:100px;}\r\n");
      out.write(".wrap-login p{width: 264px; font-size: 30px;font-weight: 500;text-align: center;}\r\n");
      out.write(".wrap-login .fieldset{width: 264px}\r\n");
      out.write(".wrap-login #form1{width: 264px}\r\n");
      out.write(".wrap-login .box-login{width: 264px}\r\n");
      out.write(".wrap-login .sect-login{width: 264px}\r\n");
      out.write(".wrap-login .sect-login .login-option{width: 264px}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* S [U20201223] 네이버 로그인 버튼추가\r\n");
      out.write("	Description:\r\n");
      out.write("	- 기존코드\r\n");
      out.write("	.box-login{padding:70px 0 0 132px; border-bottom:2px solid #898987;padding-top:50px;height: 246px;}\r\n");
      out.write("	- 추가\r\n");
      out.write("	.btn_loginNaver{display:inline-block; margin-top:35px;}\r\n");
      out.write("*/\r\n");
      out.write("/*.box-login{padding:30px 0 0 132px; border-bottom:2px solid #898987; height: 266px;}*/\r\n");
      out.write(".btn_loginNaver{display:inline-block; margin-top:35px;}\r\n");
      out.write("\r\n");
      out.write("/* E [U20201223] 네이버 로그인 버튼추가 */\r\n");
      out.write(".box-login > p{ font-size:11px;}\r\n");
      out.write(".box-login .login{ position:relative;margin-top:15px}\r\n");
      out.write("/* S [U20201223] 네이버 로그인 버튼추가\r\n");
      out.write("	Description:\r\n");
      out.write("	- 퍼블시 시스템팝업 안나오고 class 'error' 부분이 생성되면서 화면 깨짐\r\n");
      out.write("	- 개발시 시스템팝업 나오고 class 'error' 부분이 생성안되면 추가하지 않아도됨\r\n");
      out.write("*/\r\n");
      out.write("/* E [U20201223] 네이버 로그인 버튼추가 */\r\n");
      out.write("\r\n");
      out.write(".box-login .login input[type=\"text\"], .box-login .login input[type=\"password\"]{ display:block; width:135px; height:35px; padding:0 5px 0 40px; border:2px solid #b5b5b5; line-height:33px;}\r\n");
      out.write(".box-login .login input[type=\"text\"]{ margin-bottom:5px; background:url('../images/sprite_icon.png') 12px -230px no-repeat;}\r\n");
      out.write(".box-login .login input[type=\"password\"]{ background:url('../images/sprite_icon.png') 12px -261px no-repeat;}\r\n");
      out.write("\r\n");
      out.write("/* 로그인 최종버전 */\r\n");
      out.write(".box-login button[type=\"submit\"] > span {display:block;width:258px;height:36px; border:1px solid #ffff; color:#f8f8f8; font-size:15px; font-weight:500;}\r\n");
      out.write(".box-login .login > button[type=\"submit\"] {position:absolute; top:0; left:198px; display:block; width:100px; height:86px; padding:2px; background:#fb4357; line-height:78px; text-align:center;}\r\n");
      out.write(".sect-login > .box-login fieldset {position:relative ;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*140804 로그인 UI 수정 및 캡챠 시작 */\r\n");
      out.write(".box-login .login input[type=\"text\"], .box-login .login input[type=\"password\"] {width:264px}\r\n");
      out.write(".box-login button[type=\"submit\"] {width:264px;height:42px;line-height:37px;left:0;position: static;margin-top: 5px;padding:2px;background:#fb4357;text-align:center;}\r\n");
      out.write("\r\n");
      out.write("/* S [U20201223] 네이버 로그인 버튼추가\r\n");
      out.write("	Description:\r\n");
      out.write("	- 기존코드\r\n");
      out.write("	.box-login fieldset > .login-option {margin-top: 10px!important;text-align: right;width: 264px;padding-left: 0!important;}\r\n");
      out.write("*/\r\n");
      out.write(".box-login fieldset > .login-option {position:absolute; bottom:-24px; left:55px;/*top:169px; right:145px;*/ padding-left: 0!important;}\r\n");
      out.write("/* E [U20201223] 네이버 로그인 버튼추가 */\r\n");
      out.write("\r\n");
      out.write(".box-login fieldset > .login-option a {background-position:right 4px !important;}\r\n");
      out.write(".sect-login > .box-login fieldset .save-id {position:absolute; top:166px; left:-3px}\r\n");
      out.write("/* S [U20201223] 네이버 로그인 버튼추가\r\n");
      out.write("	Description:\r\n");
      out.write("	- 아이디 저장 마우스 오버시 손가락모양으로 변경\r\n");
      out.write("*/\r\n");
      out.write(".sect-login > .box-login fieldset .save-id input[type=\"checkbox\"],\r\n");
      out.write(".sect-login > .box-login fieldset .save-id label{cursor:pointer}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*140804 로그인 UI 수정 및 캡챠 끝 */\r\n");
      out.write("\r\n");
      out.write("/* 로그인 최종배포 후 삭제 */\r\n");
      out.write(".box-login fieldset > .login-option label {margin-right:20px; font-size:11px;}\r\n");
      out.write(".box-login fieldset > .login-option a {display:inline-block; margin-left:5px; padding-right:8px; background:url('../images/common/bg/bg_arrow03.png') right 1px no-repeat; font-size:12px; text-decoration:underline;}\r\n");
      out.write("\r\n");
      out.write(".box-login.nomember{ height:265px; padding:30px 0 0 0;}\r\n");
      out.write(".box-login.nomember .box-btn{ margin-bottom:30px;}\r\n");
      out.write(".box-login.nomember .box-btn > strong{ display:inline-block; margin-right:20px; color:#222222; font-size:15px; font-weight:300;}\r\n");
      out.write(".box-login.nomember .box-operationguide{ padding:20px 0 20px 40px; border:none; border-top:2px solid #e9e9de; background:none;}\r\n");
      out.write(".box-login.nomember .box-operationguide dt{ text-align:right;}\r\n");
      out.write(".box-login.nomember .box-operationguide dd{ padding:5px 0 0 0; border-left:none; background:url('../images/common/bg/dot_horizontal.gif') 0 0 repeat-x;}\r\n");
      out.write(".box-login.nomember .box-operationguide dt + dd{ padding-top:0; background:none;}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    $(\"#txtUserId\").on('keypress', function(e) {\r\n");
      out.write("        if(e.which === 13) {\r\n");
      out.write("            e.preventDefault(); \r\n");
      out.write("            let id = $(\"#txtUserId\").val();\r\n");
      out.write("            if(id === \"\") {\r\n");
      out.write("                alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#txtPassword\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(\"#txtPassword\").on('keypress', function(e) {\r\n");
      out.write("        if(e.which === 13) { \r\n");
      out.write("            e.preventDefault(); \r\n");
      out.write("            let pw = $(\"#txtPassword\").val();\r\n");
      out.write("            if(pw === \"\") {\r\n");
      out.write("                alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#submit\").click();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write("	function checkNull(){\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	//alert(\"클릭되었음\")\r\n");
      out.write("	let id = $(\"#txtUserId\").val();\r\n");
      out.write("	let pw = $(\"#txtPassword\").val();\r\n");
      out.write("	\r\n");
      out.write("   // alert(id)\r\n");
      out.write("   // alert(pw);\r\n");
      out.write("	\r\n");
      out.write("    // ID나 비밀번호가 비어 있는지 확인\r\n");
      out.write("    if(id === \"\" && pw === \"\") {\r\n");
      out.write("        alert(\"ID와 비밀번호를 입력해주세요.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    } else if(id === \"\") {\r\n");
      out.write("        alert(\"ID를 입력해주세요.\");\r\n");
      out.write("        return false; \r\n");
      out.write("    } else if(pw === \"\") {\r\n");
      out.write("        alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("        return false; \r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 실컨텐츠 시작 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- S Header -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- E Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- S 로그인 세션 확인  -->\r\n");
      out.write("<!-- prevPage에 값이 있다면 이전페이지 저장 -->\r\n");
      out.write("<!-- 저장되어있지 않다면 기본값 index.html로 저장 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

String prevPage ="";
String id = (String)session.getAttribute("id");




if (request.getParameter("prevPage")==null){
	prevPage="index.html";
}else{
	prevPage=request.getParameter("prevPage");
}




if (id != null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("var prevPage = \"");
      out.print( prevPage );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("window.location.href = prevPage;\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- E 로그인 세션 확인  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Contaniner -->\r\n");
      out.write("	<div id=\"contaniner\"  class=\"\"><!-- 벽돌 배경이미지 사용 시 class=\"bg-bricks\" 적용 / 배경이미지가 없을 경우 class 삭제  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap-login\" style=\"margin: 0px auto;\">\r\n");
      out.write("    <div class=\"sect-login\" style=\"margin: 0px auto;\">\r\n");
      out.write("        <ul class=\"tab-menu-round\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"box-login\">\r\n");
      out.write("            <h3 class=\"hidden\">회원 로그인</h3>\r\n");
      out.write("            <form id=\"form1\" method=\"post\" action=\"loginAction.jsp\" novalidate=\"novalidate\" onsubmit=\"return checkNull()\" >\r\n");
      out.write("            <fieldset>\r\n");
      out.write("                <legend>회원 로그인</legend>\r\n");
      out.write("                <p>로그인</p>\r\n");
      out.write("                <div class=\"login\">\r\n");
      out.write("                    <input type=\"text\" title=\"아이디\" id=\"txtUserId\" name=\"txtUserId\" data-title=\"아이디를 \" data-message=\"입력하세요.\" required=\"required\" />\r\n");
      out.write("                    <input type=\"password\" title=\"패스워드\" id=\"txtPassword\" name=\"txtPassword\" data-title=\"패스워드를 \" data-message=\"입력하세요.\" required=\"required\" />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("                <button type=\"submit\" id=\"submit\" title=\"로그인\"><span>로그인</span></button>\r\n");
      out.write("                <input type=\"hidden\" id=\"prevPage\" name=\"prevPage\" value=");
      out.print( prevPage );
      out.write(" >\r\n");
      out.write("                <div class=\"login-option\">\r\n");
      out.write("                     \r\n");
      out.write("                    <a style=\"cursor:pointer;\" onclick=\"location.href='findId.jsp'\"  target=\"_blank\">아이디 찾기</a>\r\n");
      out.write("                    <a style=\"cursor:pointer;\" onclick=\"location.href='findPw.jsp'\" target=\"_blank\">비밀번호 찾기</a>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("            </form>  \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>    \r\n");
      out.write("    <div class=\"sect-loginguide\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		<!-- S 예매하기 및 TOP Fixed 버튼 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sideTicketingAndTop.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- E 예매하기 및 TOP Fixed 버튼 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 실컨텐츠 끝 --> \r\n");
      out.write("<!-- E Contaniner -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- S footer_area -->\r\n");
      out.write("		\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- E footer_area -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
